### ISSUE TITLE
Add-ons are not started

### ISSUE THREAD

**Issue by tmssngr** [Betterbird/thunderbird-patches#103]
My add-ons "Allow HTML Temp", "Folder Account", "Provider for Google Calendar", "Quicktext", "Simple Mail Redirection" are not started when launching Betterbird portable, though the checkbox is blue. I have to disable and re-enable (blue checkbox -> gray -> blue) them to work. These add-ons worked fine in Thunderbird.

Windows 11, 22H2, Intel-based

**Comment by Betterbird** [comment]
This is a know issue (or call it "feature") mentioned in the support pages at https://www.betterbird.eu/support/:

--

By popular demand, Betterbird ships officially as a portable version, but it has the same issues mentioned above. We've written our own simple launcher program, BetterbirdLauncher.exe whose source is [published](https://github.com/Betterbird/thunderbird-patches/tree/main/BetterbirdLauncher). In July 2022 we got a bug report that add-ons didn't work any more when moving or renaming the portable profile. We fixed this by removing the add-on startup cache which also records native absolute path names. **With the new version we also get complaints about add-ons or themes not working.** The solution to these problems is setting preference extensions.startupScanScopes to 5 (or 7 when using light weight themes) in the Config Editor.

--

Maybe we should roll back the launcher and make the people unhappy who move their profiles since the are in the minority. Or you can switch back to the previous launcher:

https://github.com/Betterbird/thunderbird-patches/commits/main/BetterbirdLauncher/BetterbirdLauncher.exe

https://github.com/Betterbird/thunderbird-patches/raw/c40902fbe376f1799ce1131dd70067ad0aa1d442/BetterbirdLauncher/BetterbirdLauncher.exe

**Comment by tmssngr** [comment]
Do I understand your support paragraph right: with the previous launcher some people complained that their add-ons/themes were not working. But now it happens for all users (of the portable bundle)?

**Comment by Betterbird** [comment]
Yes, it's a little schizophrenic ☹️ - First the people who moved their profile were affected, that got fixed, and later it was discovered that the "fix" affected all "regular" users. And then we left it there. Sorry. We should revert back to the previous launcher. It's not that we had a flood of complaints.

For now, please set the pref to 5 or 7 or use the old launcher linked two comments above.

**Comment by tmssngr** [comment]
The previous launcher solved the problem for me.
