### ISSUE TITLE
Polish translation support

### ISSUE THREAD

**Issue by alkuzad** [Betterbird/thunderbird-patches#108]
I see that pt-BR and it are supported but polish is not, even if they are similar in installations % - https://stats.thunderbird.net/#platlang

Is there some written guideline how to add translations? Can this be automated or made simpler by using tools like Docker that will streamline process of compiling the patches ?

I also think that current TB approach with installers per language is insuficient and I had to create my own installer https://github.com/alkuzad/scoop-bucket/blob/master/bucket/thunderbird-polish.json because normally people just publish english one :) If this could be just a switch in the UI it would be better approach.

**Comment by Betterbird** [comment]
To add a translation, you need to provide the stings in a Windows cmd file like here for de, fr, es-AR, pr-BR, etc.:
https://github.com/Betterbird/thunderbird-patches/tree/main/102/scripts

If you install a language pack, you can switch between languages on the fly (with restart). I have a few installed:
![image](https://user-images.githubusercontent.com/86832723/208310159-e55b6500-9c60-4450-8b47-86dd738599ea.png)

**Comment by alkuzad** [comment]
@Betterbird I compared it and fr and they are not equal, what should I base on ? I see that in PL translations files in TB there are missing movemail definitions cause this feature was removed ([then revived ?](https://bugzilla.mozilla.org/show_bug.cgi?id=1727931))

**Comment by Betterbird** [comment]
fr, it, nl, pt-BR and ed-AR are all good staring points (de, ja and Chinese are not), they are "mostly" equal, of course the strings are different and some have the `:: Fix missing ! in the about box.`. The French doesn't have it since they already use a `.` in that string. It's already correct for Polish, see here:
https://searchfox.org/l10n/rev/961889168ba84fec326316e8fa32323448ed9fdf/pl/mail/chrome/messenger/aboutDialog.dtd#50

So based on that, you can start with fr.

Yes, the movemail strings were removed, but for Polish you can get them from here:
https://hg.mozilla.org/l10n-central/pl/file/619e43c2d9f9374c770f964c810182d978b5d74e/mail/chrome/messenger/localMsgs.properties#l102

**Comment by Betterbird** [comment]
Do you need a hand? Meanwhile we've added Albanian translation.

**Comment by alkuzad** [comment]
@Betterbird I do not have time to implement this, sticking with TB for now :)

**Comment by Betterbird** [comment]
Done.
