### ISSUE TITLE
Clarify Filter UI's nesting levels

### ISSUE THREAD

**Issue by ThiloteE** [Betterbird/thunderbird-patches#133]
### Purpose of Issue:

Clarify Filter UI's nesting levels to avoid user error as described in https://github.com/Betterbird/thunderbird-patches/issues/60#issuecomment-1146206640. Video of user error is here: https://github.com/Betterbird/thunderbird-patches/issues/60#issuecomment-1145941511

> 
> Thanks for the video. It clearly shows a user error. You are creating an empty group which will not be saved. The last two conditions are not part of the preceding group header. Compare your construct
> ![image](https://user-images.githubusercontent.com/73715071/228811794-b10b7904-0408-4231-9f8f-f42786023ac0.png)
> 
> 
> to what you intended to do:
> ![image](https://user-images.githubusercontent.com/73715071/228811830-69a1720d-fd7c-41f8-b9e4-4685d3ce63c9.png)

### Proposed solutions:

- https://github.com/Betterbird/thunderbird-patches/issues/60#issuecomment-1488405522
   ![image](https://user-images.githubusercontent.com/73715071/228814502-83a2f03a-c1c6-4b49-9ada-96f99574084e.png)

- change CSS Option 1:
    > 
    > https://github.com/Betterbird/thunderbird-patches/blob/093685292c44b63e9cfd32d3219e75a83690db9d/102/bugs/297852-grouping-search-term.patch#L1850
    > 
    > You could try in the inspector and submit the changed CSS.

    
- Change CSS Option 2
    >
    >    ![image](https://user-images.githubusercontent.com/73715071/228812911-f5b879d3-6690-4194-8d90-0a6d764d9cce.png)
    > 
    >    That's
    > 
    >       margin-inline-start: 35px;
    >       border-left: 1px solid blue;
    >       padding-inline-start: 5px;
    >   
    >   instead if the original padding-inline-start: 40px;.

**Comment by ThiloteE** [comment]
@RealRaven2000 @Betterbird you can continue your conversation here.

**Comment by Betterbird** [comment]
@ThiloteE, thanks for creating a new ticket. The issue is more complicated, you will need multiple tree-lines:

![image](https://user-images.githubusercontent.com/86832723/228931121-f7cdec44-71f7-483d-9ea4-c0a0ae3538ba.png)

So in each row, you'd have to add some SVG of various "shapes". That's all the pain of visualising a decision **tree** as a list.

**Comment by RealRaven2000** [comment]
My suggestion was a little more light weight - only use the tree nodes on search notes (not the overarching group nodes) :

![image](https://user-images.githubusercontent.com/6314674/228517250-2b54cde2-a939-45b4-9bd1-c43551524d76.png)

this would only require 2 types of icons, one for then "end of group" and one for any previous element. I think this would already add all the clarification needed. The idea was that whatever search terms were added to a group they would need to be indented under a line "Match all /any" to belong to it.

**Comment by Betterbird** [comment]
Why don't you "adorne" my example with the lines at you envisage them? You will notice that you need two lines 😉 

![image](https://user-images.githubusercontent.com/86832723/228960134-db3f37c8-0b8f-42cd-a321-4c172b97235f.png)

**Comment by RealRaven2000** [comment]
Like I said, I would only do it on conditions (not on the groups) - like this:

![image](https://user-images.githubusercontent.com/6314674/229255665-13d0718a-a24b-47cb-86f7-f740d89bc9b3.png)

that would be clear enough for me

**Comment by Betterbird** [comment]
I don't think this is enough, please consider these:
![Ex1](https://user-images.githubusercontent.com/86832723/229273526-ac0404dd-dc51-4372-aa09-cd44ca508b1a.png)
![Ex2](https://user-images.githubusercontent.com/86832723/229273539-15d64640-2bd5-44f6-b5d6-b17ba22f04a9.png)
These are two of my test cases.

**Comment by RealRaven2000** [comment]
This is what I would do - again, sticking to the rule of only "decorating" the rules, not the groups:

![image](https://user-images.githubusercontent.com/6314674/229287292-bee26b93-45c6-4874-8a97-b24ad842788c.png)

![image](https://user-images.githubusercontent.com/6314674/229287418-c2a2fec7-3584-43b5-82b3-97f040d4a420.png)

personally I wouldn't try to create connection lines that go across the "group" nodes, because I think it might make it look more cluttered and would be harder to implement. but if you think it would need them I would make them 

1) as marching ants pattern
2) I would not connect them to the groups. e.g. like this:

![image](https://user-images.githubusercontent.com/6314674/229287683-00202c73-6658-4ea4-90a2-729374b3218d.png)

but I think that looks more cluttered and is probably harder to implement on top of that.  IN the examples above, they brain is well capable of "filling in the missing lines".

**Comment by Betterbird** [comment]
All a matter of taste, but I got your point now, thanks. Yes, your suggestion is easier to implement, likely just an an SVG before the conditions.

**Comment by RealRaven2000** [comment]
I think it would also be much cleared if you happened to accidentally create an "empty group" - which is why I made the suggestion in the first place:

![image](https://user-images.githubusercontent.com/6314674/229287871-ba6afabd-ba07-489d-9475-20480d46c1df.png)

this makes it very obvious that the second term (subject contains b) is not in the second group, and that there is only one term in the second group (subject contains d)

PS: I am not proposing drag and drop to fix this! :)

**Comment by Betterbird** [comment]
Uff, did you edit the image moving "contains b" to the left? I hope the software doesn't allow to create something like this.

You mean the second group only has "contains c" (not d). "Contains d" now hangs in mid-air, it used to below to the first group before your photoshopping broke everything 😢

**Comment by RealRaven2000** [comment]
> Uff, did you edit the image moving "contains b" to the left? I hope the software doesn't allow to create something like this.
> 
Yes I only used Photoshop, this was a hypothetical case showing a broken filter. I don't even think it can be stored that way. But remember the starting point of the conversation: creating a hanging group that has no content. This just illustrates the point that you might have a new group without content and might think the search term below (which is not indented) may belong to it - the indentation lines on the left make it abundantly clear that it doesn't belong to that group.

> You mean the second group only has "contains c" (not d). "Contains d" now hangs in mid-air, it used to below to the first group before your photoshopping broke everything 😢

Yes, it's just photoshopped - and may make no sense semantically.

In the (maybe impossible) doctored screenshot I am just basing the graphics on the visual indentation levels, (which I guess result from the grouping) and here the "d" line is underneath the second group (which could probably be changed to use "any" instead of "all" to add more realism - I am not claiming that it may be possible to edit that way. The salient point here is just that "subject contains b" is not under the second group but the very first (top) one. (The following lines may well be nonsensical). But I just assumed that it may be possible to break the filter somehow when editing stuff out of order. 

The following should be possible, right? (Again, just created in Photoshop)

![image](https://user-images.githubusercontent.com/6314674/229292685-171169a8-5646-421d-94b0-40127ff734e7.png)

in this example, the main point is that we clearly have no conditions in the 2nd group. One would need logic that only allows the "elbow" graphic for any last search term within a group (term `e`), all previous elements should have the "connector" graphics, even if there is new group within the elements (see terms `a` and `b`).

**Comment by Betterbird** [comment]
OK, if you just want the "T" and the "L" in front, this can be done in CSS alone, like so:

`padding-inline-start: 20px; background-image: url('chrome://global/skin/icons/warning.svg'); background-repeat: no-repeat; background-position: 10px center`. You just have to define suitable SVGs, add them somewhere and reference them like this. The position of course depends on how much the term is indented. Depending on the SVG width, maybe about 10px less then the indentation. The JS code can use the appropriate image depending on whether it's the last term in the group. So the CSS needs to be updated when terms are deleted to or added from the group. Not a big deal since there is already code that moved the start/end group markers.

![image](https://user-images.githubusercontent.com/86832723/229377405-f0925ce8-2f8c-49f6-9848-a12943a9f544.png)

**Comment by Betterbird** [comment]
This is what I have now:
![image](https://user-images.githubusercontent.com/86832723/229637183-e282d226-d7c2-43c9-9f8c-f3e8718a3768.png)

The patch is still WIP with some edge cases not working.

**Comment by RealRaven2000** [comment]
> This is what I have now: 

this looks very good, alignment & thickness are perfect. Just 1 minor nit - I would choose slightly lighter grey, maybe the same gray as the outline of the text fields #B3B3B3 instead of the much darker current #7F7F7F. This attracts too much attention. Here the same screenshot with the lighter gray:

![image](https://user-images.githubusercontent.com/6314674/229649552-d32d7c2c-d016-4aa5-8bf6-2aed09b79790.png)

I know this is subtle but I think it is even better.

**Comment by Betterbird** [comment]
Done.

**Comment by Betterbird** [comment]
Works fine now for complicated cases like this one:

![image](https://user-images.githubusercontent.com/86832723/229859290-b5163d27-d134-4bc3-8c2e-16be9c5d982d.png)

**Comment by ThiloteE** [comment]
Awesome :)

**Comment by Betterbird** [comment]
You can try it out:
Windows: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-102.9.1-bb32-latest-build.en-US.win64.installer.exe
Linux: (coming soon)

**Comment by RealRaven2000** [comment]
that's even better! You added nodes for the groups as well - I thought this might be difficult. Looks great, very instructive!

**Comment by RealRaven2000** [comment]
> Try to break it and then post a "broken" picture here (or send to our support). We'll ship this in BB 102.10.0-bb33 after Easter.

challenge accepted! :) I guess I have to do it without Photoshop? :P

**Comment by Betterbird** [comment]
Uploaded a new build for Windows only adding this functionality also to the search, virtual folders, mail views(*) and AB(**) search windows.

(*) Need to configure this button
![image](https://user-images.githubusercontent.com/86832723/230055902-f3e07557-6386-419c-b310-0369c6396951.png)
then Customize... > Edit.
(**) View AB, Edit > Find > Search Addresses.

**Comment by RealRaven2000** [comment]
Looking good:

![image](https://user-images.githubusercontent.com/6314674/230080510-d5b04075-fdb6-4336-9446-e2259a51975b.png)

second part:

![image](https://user-images.githubusercontent.com/6314674/230080954-8929ed67-c97b-47bb-b50d-4b78e971571d.png)


... for some reason I cannot increase the dialog window height when I edit a search folder via folder / properties (hence the screenshot is in 2 parts here)... - Windows 10 Professional.

**Comment by Betterbird** [comment]
Grrr, yes, this panel doesn't allow resize. I though that "testing" this would just involve opening some filters/searches.

The new functionality is additional, that is, no logic was changed, there is just some more code to add CSS.
