### ISSUE TITLE
Show current selected message in message pane during multiple selection

### ISSUE THREAD

**Issue by XP1** [Betterbird/thunderbird-patches#136]
When I multiselect, I want the message pane to show the latest message that I clicked on. I'm still clinging to discontinued abandonware Windows Live Mail (WLM) 2012 for this most beloved feature. It makes so much sense that I can quickly select, view, and delete emails in one combined action.

You can see an example of how WLM does this:
https://xp1.github.io/Critical-features-of-email-clients/

In other email clients where the feature doesn't exist, I have to view every email and delete them one by one or go back and remember which emails that I viewed in order to select and delete. It's not practical.

In Thunderbird, the conversation summary in the message pane is pretty useless. The message list pane already shows which messages are selected anyway. There's no need to duplicate that in the message pane.

There is a patch by Mats Palmgren on Bugzilla from 17 years ago. Do you think it still works?

[FIX] Would like to see the preview pane show last select msg when selecting multiple msgs:
https://bugzilla.mozilla.org/show_bug.cgi?id=364896

Patch rev. 1, Mats Palmgren:
https://bugzilla.mozilla.org/attachment.cgi?id=249598
https://bugzilla.mozilla.org/attachment.cgi?id=249598&action=diff
https://github.com/Betterbird/thunderbird-patches/files/11142589/patch1.diff.patch

**Comment by Betterbird** [comment]
The patch (are three links to it really required?) doesn't apply any more, it would have to be developed again. As mentioned in the bug, you will need a preference to enable this behaviour. Other than that, it's doable. Any incentive you can offer?

**Comment by Betterbird** [comment]
This really is a neat idea. We'll ship it in BB 102.10.0-bb33 next week. Set pref: mail.multiselect_message_shows_current to enable.
Preview in: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-102.9.1-bb32-latest-build.en-US.win64.installer.exe

Note that news folders already don't have a multi-select summary. However, the message display shows the first selected message and not the one that was last added to the selection with, for example, Shift+Downarrow. With our change, this will be a lot more useful.

Note that the feature will be difficult to implement for the upcoming version 115 since the entire message display pipeline was reworked and the feature of having folders not summarised broke, see https://bugzilla.mozilla.org/show_bug.cgi?id=1826633.

Since you got the feature without offering any incentive, at least you should mention in bug [364896](https://bugzilla.mozilla.org/show_bug.cgi?id=364896) that the feature was implemented in Betterbird via:
https://github.com/Betterbird/thunderbird-patches/blob/main/102/features/18-feature-multiselect-shows-current.patch

**Comment by Betterbird** [comment]
http://www.betterbird.eu/media/img/multiselect.mp4

**Comment by XP1** [comment]
Thanks, that was fast. Don't worry, I sent a donation.

I did notice that multi-selecting a message above marks as read but multi-selecting a message below does not.

**Comment by Betterbird** [comment]
Thanks. We'd still appreciate a comment in bug 364896 so the upstream project will know that they can improve easily if they wish.

We've noticed the suboptimal "mark as read" behaviour depending on the selection direction (up works, down doesn't), we'll take a look.

**Comment by Betterbird** [comment]
Turned out that the new pref interfered with an existing one, `mail.operate_on_msgs_in_collapsed_threads`. If that's set to false, there's also no summarising happening, and with the reduced patch the last message in a multiselect is still displayed as desired.

We noticed that setting `mail.operate_on_msgs_in_collapsed_threads` to false in TB, doesn't mark any multi-selected message as read, regardless of whether going up or down. So this behaviour is caused by the patch alone. We'll look into it further.

**Comment by Betterbird** [comment]
OK, so here's a build that fixes the up/down selection issue:
https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-102.9.1-bb32-latest-build-take2.en-US.win64.installer.exe
As we wrote above, pref `mail.multiselect_message_shows_current` was removed again, now you need to set pref `mail.operate_on_msgs_in_collapsed_threads` to false.

We'll have to see how this pans out in the upcoming version 115. Maybe we'll bring the new pref back if we can untangle it better.

**Comment by Betterbird** [comment]
OK, after looking at the upcoming version 115, we decided that it would be desirable to allow pref `mail.operate_on_msgs_in_collapsed_threads` and pref `mail.multiselect_message_shows_current` to work independently. The former one is `true` by default and allows mass operations on collapsed threads, which is a bonus. In the latest version you can leave this at `true` and set the newly re-introduced pref `mail.multiselect_message_shows_current` to true again without affecting the other functionality.
