### ISSUE TITLE
The program tray icon doesn't look too good - perhaps the users could pick their favorite?

### ISSUE THREAD

**Issue by unalignedcoder** [Betterbird/thunderbird-patches#151]
This is definitely a minor issue but, at least on Windows, the tray icon in particular looks quite ugly. 

![image](https://user-images.githubusercontent.com/16850566/235306090-b368ff53-15da-403c-87a2-19fa636723e5.png)

A great improvement would be an option to give the user a choice on what program icon to use.

The program icon can be changed replacing `messengerWindow.ico` in the program's `chrome` folder, but this unfortunately doesn't take care of the tray icon...

**Comment by Betterbird** [comment]
The tray icon isn't ideal, here seen with the Windows magnifier:
![image](https://user-images.githubusercontent.com/86832723/235315056-174946e8-9487-4045-b5ee-42cac0a96d2f.png)
That's because (at least) Windows 10 still uses 16x16 icons, it's better in most Linux desktops.

You're right that changing `C:\Program Files\Betterbird\chrome\icons\default\messengerWindow.ico` changes the taskbar icon but not the systray icon. We'll check what the mechanism is and potentially improve it. Strangely the newmail icon isn't installed anywhere, yet it's displayed in the systray.

**Comment by Betterbird** [comment]
We looked at this some more, and yes, it can be done if where change these calls to `LoadIcon()` 
https://searchfox.org/comm-central/rev/cbd8afe916f94a039bb9cbbbd66f3a5fb98395be/mailnews/base/src/nsMessengerWinIntegration.cpp#362,381
which use static resources compiled into the program to using dynamic icons created with `CreateIcon()` similar to this code
https://searchfox.org/comm-central/rev/cbd8afe916f94a039bb9cbbbd66f3a5fb98395be/mozilla/widget/windows/SystemStatusBar.cpp#192-197

---

Just for the record, this is the first version of the comment which shows how we got to this result:

So the issue of changing the program icon isn't new, see Issue #83 and Issue #92. In we commented that the icon are actually **in** the executable and that you can manipulate them with something like [Resource Hacker](http://www.angusj.com/resourcehacker/). Here's a screenshot using the tool:

![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/1b5fda57-0320-4e35-8635-6cdb5d335954)

Looks like the icons are defined as resources here:
https://searchfox.org/comm-central/rev/cbd8afe916f94a039bb9cbbbd66f3a5fb98395be/mail/app/splash.rc#19-20
and then accessed via `IDI_APPLICATION` or `IDI_MAILBIFF` using `LoadIcon()`:
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadicona
The documentation states: `hInstance`: A handle to an instance of the module whose **executable file contains the icon** to be loaded.
Even the replacement function (https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadimagea) has the same description of the parameter.

BTW, if you remove C:\Program Files\Betterbird\chrome\icons\default\messengerWindow.ico, the program defaults to the standard mail icon.

We were a bit surprised to learn from your report that the program icon in the taskbar can be changed by storing a different icon file under C:\Program Files\Betterbird\chrome\icons\default\messengerWindow.ico. According to [this article](https://stackoverflow.com/questions/18493442/how-to-change-the-icon-in-taskbar-using-windows-api) you can use this Windows API `SendMessage(hwnd, WM_SETICON, ICON_SMALL, hIcon);` to change the taskbar icon, and it appears that such calls are used in the Mozilla platform code, see here:
https://searchfox.org/comm-central/search?q=SendMessage.*wm_seticon&path=&case=false&regexp=true
However, we still haven't tracked how the icon from the chrome directory is set there, but we can do that later. But that only sets the taskbar and not the systray.

Starting with this query https://www.google.com.au/search?q=How+to+change+the+icon+in+systray+using+windows+api (analog to the article quoted above), we got here:
https://stackoverflow.com/questions/4964630/system-tray-icon-in-c
and to this demo:
https://www.codeproject.com/Articles/74/Adding-Icons-to-the-System-Tray
We signed up to the site, downloaded the demo and found code inside using, surprise, surprise: `LoadIcon()` and `LoadImage()`, which we know refer to resources.

Further reading here https://learn.microsoft.com/en-us/windows/win32/menurc/using-icons, quote:
An application should implement custom icons as resources and should use the [LoadIcon](https://learn.microsoft.com/en-us/windows/desktop/api/Winuser/nf-winuser-loadicona) or [LoadImage](https://learn.microsoft.com/en-us/windows/desktop/api/Winuser/nf-winuser-loadimagea) function, rather than create the icons at run-time.

That page also gives an example for creating icons on the fly, but is seems that quite a bit of Windows system programming would be needed to make this happen. The `CreateIcon()` call is used in the Mozilla platform code
https://searchfox.org/comm-central/search?q=createicon%28&path=&case=false&regexp=false
in the context of changing the taskbar icon dynamically.

Looks like it could be made to work by changing the `LoadIcon()` calls here
https://searchfox.org/comm-central/rev/cbd8afe916f94a039bb9cbbbd66f3a5fb98395be/mailnews/base/src/nsMessengerWinIntegration.cpp#362,381
to using dynamically created icons like here:
https://searchfox.org/comm-central/rev/cbd8afe916f94a039bb9cbbbd66f3a5fb98395be/mozilla/widget/windows/SystemStatusBar.cpp#192-197.

**Comment by Betterbird** [comment]
OK, this is done now. If you replace messengerWindow.ico and newmail.ico, they will be reflected in the systray:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/a565ef12-7b85-4025-89b9-6cd75b22d4fc)
The thing that looks like Saturn is an only SeaMonkey icon we used for testing (and the other one is OpenRBG unrelated to the work here). With the newmail.ico also changed to the TB Daily icon, it looks like this:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/b6f5dd9a-aaab-4d0e-bc12-67124230acb1)

Test version here: https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-102.11.0-bb35-latest-build.en-US.win64.installer.exe

FInal thought: Different icons were high on the wish list in our recent survey, so this gets us one step closer.

**Comment by Betterbird** [comment]
Had to rebuild everything due to a bug, so this is now already in the official version (and the latest build was deleted).

**Comment by Betterbird** [comment]
We've documented how to configure the icons on our [expert tips page](https://www.betterbird.eu/expert-tips/index.html#custom-icons). The current (un)installer still removes the messengerWindow.ico file, but with the next version the icons the users stores into C:\Program Files\Betterbird\chrome\icons\default\ will be preserved.

**Comment by unalignedcoder** [comment]
It's great that we can now customize both those icons. If would be great it there also was an "unread" icon. Often I forget I have unread messages buried into some folder, but the newmail icon only shows where there a new ones.

**Comment by Betterbird** [comment]
You can control this with pref `mail.biff.use_new_count_in_badge`, also exposed in the UI:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/60fd7ca2-6087-4f8d-9026-338af7aaacaa)


Set to false and it will track the unread messages. This is pretty useless for people who are subscribed on mailing lists and have thousands of unread messages. But give it a try.
