### ISSUE TITLE
Documentation: Message Search/Filtering "matches"/"doesn't match" Conditions

### ISSUE THREAD

**Issue by RespiteSage** [Betterbird/thunderbird-patches#164]
## Quick Summary

Please document that the `matches` search/filtering condition uses case-insensitive regular expressions following the syntax in ECMAScript 3rd Edition.

## Background

I was recently messing around with message filtering for the first time when I noticed a "matches" condition. However, it wasn't clear to me what the pattern syntax was for matching, and I didn't want to test it on my actual emails. After a fair amount of searching, I realized that I should've been using the search terms "regex" and "regular expression", which turned up in [the release notes](https://www.betterbird.eu/releasenotes/index.html). However, that wasn't a full answer because I still didn't know what regex standard was being used. After grepping this repo, I did finally find where it's implemented in [`102/features/14-feature-regexp-searchterm.patch`](https://github.com/Betterbird/thunderbird-patches/blob/main/102/features/14-feature-regexp-searchterm.patch#L856-L905) (and the analogous patch for 115, but I'm running 102). So then I had to go figure out that [C++'s std::regex uses a particular ECMAScript standard by default](https://en.cppreference.com/w/cpp/regex/ecmascript). I also saw that Betterbird's regex matches are case-insensitive, which was actually the main question I had in the first place. I'm glad I know now, but it was unnecessarily hard to learn.

## Suggestion

Please add documentation indicating the syntax for `matches` (and `doesn't match`) message search/filtering conditions, including both the word "matches" and the phrase "regular expression" (for searchability), a reference to the specific regex standard (the one included in [ECMA-262 3rd Edition](https://262.ecma-international.org/5.1/#sec-15.10)[^1]), and a note that matching is case-insensitive. Additionally, it would probably be helpful to amend the release notes to indicate that the regex in search terms is via the `matches` and `doesn't match` conditions (again, for searchability). I've included examples below, in case that makes it easier for you to make these documentation improvements.

(I'm going to use markdown to make it easier to indicate links and formatting.)

General documentation (presumably on the Support page, since you don't seem to have any more detailed docs)
```markdown
### How do I use pattern matching for search terms?

Betterbird adds "matches" and "doesn't match" conditions for searching and filtering messages 
based on case-insensitive regular expressions. The regex matching is implemented with C++'s
std::regex library, which (almost completely) follows the regular expression syntax in the
[ECMA-262 Standard](https://262.ecma-international.org/5.1/).
```

Updated release notes
```markdown
NEW - Regular expressions in search terms (folder search and filters) via "matches" and "doesn't match" conditions (fixed in 102.7.1) - [Bug 19442](https://bugzilla.mozilla.org/show_bug.cgi?id=19442)
```

[^1]: Apparently ECMAScript 3rd Edition isn't available as online HTML, which is a bummer, but I think the linked edition should be fine?

**Comment by Betterbird** [comment]
Changed the release notes to:

NEW - Regular expressions in search terms (folder search and filters) via "matches" and "doesn't match" conditions. Note that matching is case-insensitive and is implemented using the C++ std::regex library, which (almost completely) follows the regular expression syntax in the [ECMA-262 Standard](https://262.ecma-international.org/5.1/). (fixed in 102.7.1) - [Bug 19442](https://bugzilla.mozilla.org/show_bug.cgi?id=19442)

You think this should be mentioned on a different page as well?

**Comment by RespiteSage** [comment]
I think ideally Betterbird would have thorough documentation of usage differences from Thunderbird in a format that's easy to browse, but I'm sure you would have that documentation if it was practical for you to create and maintain it. So I think updating the release notes is fine.

**Comment by Betterbird** [comment]
Just for your information: std::regex turned out to be a nightmare: 1) Needed different code for Windows and Linux/Mac. 2) Was throwing exceptions when invalid regexp was entered. In the Mozilla environment throw/try/catch are not allowed. In 115.6.0 we hacked it into place, but right after that release we replaced std::regex with ICU's regex. This has three advantages: 1) ICU code already in the Mozilla tree 2) Same code an all platforms dealing with UTF-16 strings just fine 3) No exceptions.

I wish we had consulted [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_regular_expression_engines) earlier, that would have saved a lot of time.
