### ISSUE TITLE
Restore support for vertical separators in the sort-of-a-toolbar

### ISSUE THREAD

**Issue by eyalroz** [Betterbird/thunderbird-patches#177]
I'm using BB 115.0-bb6.

Thunderbird has removed its toolbar, leaving us with some charred and disfigured remains in the form of the "unified" toolbar. However, trying to customize that one, it seems there is no option to add vertical separators (not spaces) between items.

It would be nice if you could somehow restore the option add such separators.

**Comment by Betterbird** [comment]
Please file this with TB. For now, you can do a border via userChrome.css:
```
li.go-back {
  border-left: 1px solid red;
}
```
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/4a9328db-672f-4b52-ab0a-577aa33d65b3)

We're not likely to action this since we don't really want to mess around in the UI unless absolutely necessary.
