### ISSUE TITLE
Betterbird and Mozilla-related telemetry

### ISSUE THREAD

**Issue by rjolina** [Betterbird/thunderbird-patches#184]
Does Betterbird have telemetry enabled, i.e. does it connect to Mozilla (and other) servers?

**Comment by Betterbird** [comment]
No, it doesn't and that's widely published.

https://github.com/Betterbird/thunderbird-patches/blob/c50991e1fe3476f1ab43c1cc6a5adb0f3e6c87d6/115/mozconfig#L33

https://www.betterbird.eu/legal/
Being a fork of Mozilla Thunderbird, the software collects some data about the user, less than the original Mozilla Thunderbird, as outlined in [Thunderbird's privacy statement](https://www.mozilla.org/privacy/thunderbird/). No data is submitted to Betterbird, some data may be submitted to Mozilla. Betterbird offers a product Start Page which processes access data as described above.

Also latest release notes:
FIXED - Betterbird collected data for reporting without ever submitting it. Now data collection in the datareporting folder has been completely disabled. (fixed in 102.13.0)
