### ISSUE TITLE
Lost all my previous tabs when importing my thunderbird profile

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [Betterbird/thunderbird-patches#187]
How do I get them back? Please help :{

**Comment by Betterbird** [comment]
Please do not post support requests as GitHub issues. We have a support e-mail for those.

What do you mean by "tabs". Messages opened in tabs, Account Manager, Settings, Calendar, etc.?
How to get them back? Well, what's wrong with opening them again? Look like the upgrade lost the open tabs, not a big surprise since the entire UI was re-written.

Note that TB 115 is very bad at restoring tabs, we mitigated that a bit so at least they aren't restored empty or dysfunctional, but it slows down that startup tremendously for user with lots of calendars. Sounds strange, but at startup, the Calendar competes with opening the tabs. Until this is fully fixed, we suggest not to leave any/many messages open in tabs. If that's too inconvenient, you should go back to 102 for now.

**Comment by RealRaven2000** [comment]
> How do I get them back? Please help :{

Are we talking QuickFolders? Make sure it is enabled, as it is fully compatible with BB. If you have trouble with QuickFolders contact the Add-on author (me) directly.
