### ISSUE TITLE
Can I use the AUR tbkeys package within Betterbird?

### ISSUE THREAD

**Issue by tobip** [Betterbird/thunderbird-patches#189]
I have the `thunderbird-extension-tbkeys` package from AUR installed on my system, it is located under `/usr/lib/thunderbird/extensions/`.

Is there a way to tell betterbird to use this extension?

**Comment by Betterbird** [comment]
This seems more like a support query rather than a bug report.

Betterbird supports application extensions, as per our Release Notes: https://www.betterbird.eu/releasenotes/
CHANGED - Linux: Now supporting sideloaded "application" add-ons stored in betterbird/extensions. To enable those add-ons, preference extensions.autoDisableScopes needs to be set to 3. (fixed in 102.9.1)

So set the pref, a bit value, from default 4 to 4 + 3 = 7. Copy the extension to betterbird/extensions. Let us know whether that worked.

**Comment by tobip** [comment]
Awesome!
extensions.autoDisableScopes was at 15 in my case, I set it to 18. No clue what it means, but it works. edit: it also works with 15.
The /opt/betterbird/extensions subfolder did not exist, I created it manually and copied the xpi file from the /usr/lib/thunderbird/extensions directory.

Sorry for using the issue tracker as a support line!

**Comment by Betterbird** [comment]
Umm, as we said, it's a bit value, so 15 = 1111(b). 18 = 1.0010(b), you're lucky that worked since you still have the 10(b) bit set. IOW, if it's already 15, no need to change it.

**Comment by tobip** [comment]
Yes that makes sense then, thanks for the update.
