### ISSUE TITLE
BrowserInfo name Thunderbird - intentionally?

### ISSUE THREAD

**Issue by Rimole** [Betterbird/thunderbird-patches#192]
The API provides [browser.runtime.getBrowserInfo()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getBrowserInfo)

My Betterbird says: `name: "Thunderbird", vendor: "", version: "115.1.1", buildID: "20230815110105"`

Is this intentional (for example for compatibility), that Betterbird calls itself "Thunderbird" here?

**Comment by Betterbird** [comment]
Yes. Betterbird calls itself Thunderbird almost everywhere, also in the UA string, otherwise access to ATN wouldn't work. We have considered to implement a distinction of some sort, but so far that hasn't been done. If you need to distinguish, you can get `AppConstants.MOZ_APP_VERSION_DISPLAY` or `AppConstants.MOZ_APP_DISPLAYNAME_DO_NOT_USE`.
