### ISSUE TITLE
"Unread Mail" tray icon does not appear for any folder other than Inbox

### ISSUE THREAD

**Issue by dark-penguin** [Betterbird/thunderbird-patches#197]
This is very simple to reproduce:
- Mark any email as "Unread" in Inbox -> tray icon appears
- Mark any email as "Unread" in any other folder -> tray icon does not appear

I have it configured to display "Unread" mail rather than "New" mail.

**Comment by Betterbird** [comment]
Set pref mail.notification.count.inbox_only to false and restart.

**Comment by dark-penguin** [comment]
Ohh, thanks, this helped!

**Comment by Betterbird** [comment]
There are still mailboxes in which unread messages aren't counted. The code is rather twisted:
https://searchfox.org/comm-central/rev/7340134fa7d638f1a580c7855e33a66a27d9c94a/mailnews/base/src/MailNotificationService.jsm#122

Most heavy users don't count unread messages since they have thousands of them, They are interested in keeping up with new stuff.

**Comment by dark-penguin** [comment]
I have hundreds per day. I automatically mark most of them as read and move them to another folder, so that I don't miss the important ones. Those are moved to the "Important" folder and left unread, and "Inbox" contains stuff that didn't pass any filter.

My folders are nothing special, judging by that code, so the edge case won't concern me. Thank you!
