### ISSUE TITLE
(en-US) missing at download page

### ISSUE THREAD

**Issue by Rimole** [Betterbird/thunderbird-patches#205]
No issue, but a nuisance at https://www.betterbird.eu/downloads/index.php
There are 
```
Spanish (es-AR)
Portuguese (pt-BR)
Chinese (simplified)
```
but just `English`, while the download file has in its name `en-US` (and not e.g. `en-UK`). 
I.e. there is an `(en-US)` missing after `English`.

**Comment by Betterbird** [comment]
I'm not happy with this bug report. How can a missing "en-US" be a nuisance? According to the [Oxford Dictionary](https://www.oed.com/search/dictionary/?scope=Entries&q=nuisance) _"a source of annoyance or irritation; an irksome situation or circumstance; trouble, annoyance"_.

What differences in the UI do you see between US English and UK English apart from the word "color/colour"? Am an Australian citizen and I don't have a problem with US English in software. In Betterbird there are no trucks/lorries, no movies/films, no fries/chips, no apartments/flats, no garbage/rubbish and most spellings with "z" instead of "s" are also correct in UK English. I'm sure that even in BE browser cookies are called cookies and not biscuits.

If we were to add en-US, we should also consider doing this for German since Austrian and Swiss German are considerably different from German German. And for French since French from France is different to French from Belgium or Canada.

We've added it where absolutely necessary, in particular for Portuguese which is very different between Portugal and Brazil and Chinese where simplified Chinese (mainland China) and traditional Chinese (Taiwan and Hong Kong) are very different. It's debatable whether it's needed for Spanish since the es-AR version is pretty neutral and we're only using it since traditionally it was more complete and correct than es-ES.

**Comment by Betterbird** [comment]
If you could give us some motivation why a UK English build would be good to have, we will consider it. In this case we would add en-US and en-UK to distinguish.

**Comment by Betterbird** [comment]
An English language pack was requested on a German newsgroup and on Reddit, so we created one:
https://www.betterbird.eu/downloads/get.php?os=all&lang=en-GB&version=release

Obviously to distinguish we had to add "en-US" and "en-GB" to the table now as you had requested. We hope that closes the issue.
