### ISSUE TITLE
[Feature Request] Respect system GTK theme, TB bug 1843646 (WONTFIX)

### ISSUE THREAD

**Issue by aaronliu0130** [Betterbird/thunderbird-patches#207]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1843646, which was closed by Thunderbird devs as wontfix with the spurious reason of needing to add conditional code for every single gtk theme

This is not just about colors by the way but also every single UI element

**Comment by Betterbird** [comment]
Oh boy, what have the Tb folks done now, they're ignoring the system theme :cry:. Well, their new "director" strikes again, after tossing multi-folder select, thread lines and message counts in the main window's status bar into the bin.

I'll see what we can do, but likely that would be a heap of work.

**Comment by Betterbird** [comment]
Well, we talked to some people and the information was that we'd have to go in and replace all the hard-coded TB colour with system colours. We really don't have much expertise in working on the theme, so this is likely not going to happen.

**Comment by aaronliu0130** [comment]
Hmm, is it possible to copy some of the 102 UI code to 115 despite the rewrite?

**Comment by Betterbird** [comment]
We don't have the capacity for this ticket. It would create endless conflicts with the upstream codebase if we had to constantly tweak all the CSS code.

**Comment by aaronliu0130** [comment]
![image](https://github.com/Betterbird/thunderbird-patches/assets/11874211/811cc9cd-9020-4e6b-a3bc-8ae7bba28435)

can this be displayed as not-planned then?
Are the Thunderbird styles scattered in hard code instead of being centralized?

**Comment by Betterbird** [comment]
I don't see a "not planned" label.

A while ago we asked TB's theme maintainer and his answer was:
_Only with considerable effort. You would have to have replace all hard-coded colours with the system colours._

And since that stuff is scattered all over the place, we'd create a bazillion merge issues as soon as any of the upstream TB CSS changes. Plus, it would be considerable effort to get it right in the first place with lots of testing on Linux.

Of course anything is doable, but not for free. And for the price tag of this, you could buy a small (maybe second-hand) car.

**Comment by aaronliu0130** [comment]
Ah ok, I understand.
![IMG_1815](https://github.com/Betterbird/thunderbird-patches/assets/11874211/65c12a9e-a475-4a3e-a6b2-e618f3e05307)
