### ISSUE TITLE
TB Bug 1817605 - Can't select multiple folders in new folder tree to move, delete or mark as read

### ISSUE THREAD

**Issue by spiffikins** [Betterbird/thunderbird-patches#210]
Mozilla recognizes that this is a regression bug in Supernova, but has marked it as WONTFIX - incredibly frustrating!

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

Steps to reproduce:

Can't select multiple folders in new folder tree:
Click on a folder, use Shift+Down-arrow to select multiple folders.

Actual results:

Only one folder selected.

Expected results:

Should select multiple folders.

**Comment by spiffikins** [comment]
Also 1857786,1857216,1856561,1855725,1855217 if that helps!

This is a major functionality loss - I have dozens of message filters that filter incoming mail into folders and subfolders.  I then need to mark those folders as "read" - and since "mark folder read" doesn't work on subfolders (also an open feature request for a decade) - the only option is to select multiple folders and their subfolders at once, and then use "mark folder as read"

Now I can't even do that clumsy workaround.

Thank you for reviewing this!

**Comment by Betterbird** [comment]
You won't believe it, but one of our guys filed https://bugzilla.mozilla.org/show_bug.cgi?id=1817605, check the disabled account.

So consequently we're very much aware of the bug, it's even featured at out home page.

So far we've been waiting whether the pressure on TB will come to a point where they will implement it, see [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1817605#c6):
_For now we're not planning to tackle this, but if we get many bug reports with valid workflows, we could consider it._

This is a lot of work since the a lot of code assumes that there is one current folder. We're reluctant to start implementing this just for TB to take our patch for free.

**Comment by spiffikins** [comment]
Thanks for the insight!  I'm not sure how to best add my vote/pressure to TB - is it better to submit a new bug report on this to TB or update the bug they marked as WONTFIX?

**Comment by Betterbird** [comment]
Very little will move Mozilla/MZLA/Thunderbird. I guess some initiative on social media would do it. Reddit already doesn't look so good:
https://www.reddit.com/r/Thunderbird/

**Comment by Betterbird** [comment]
We started thinking about this. In version 102, not many operations are possible on a folder multi-selection, here the context menu:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/18eaf839-184f-46d2-85a7-b1dbb58997a1)

Additionally there is drag & drop to move folders and pressing the delete key to delete them. Are we missing anything?

**Comment by Betterbird** [comment]
We took a good look a this. In TB 102 and before, both the thread tree (thread pane/message list) and the folder tree were based on the Mozilla platform class nsITreeView.

For TB's new address book implementation, the TB team implemented a new more flexible tree widget to replace nsITreeView. This is used to display the address book cards. However, for the list of address books on the left, a simple list of <ul> elements with inner <li> elements was used. This HTML structure doesn't allow for multi-selection.

In TB 115 the same model was applied to the folder "list" and the thread tree. Simple list on the left with <ul> and <li> elements, a "real" tree widget that allows multi selection. We don't know why this design was chosen, it doesn't appear sophisticated enough to handle a folder tree correctly.

In order to make this work, a whole redesign would be necessary. The changes would reach into all parts of the system, and the patch to effect this change would be huge. It would become unmanageable rather soon, since it would have to be adjusted each time the underlying code base changes, and that's about every two or four weeks.

Betterbird understands itself to be a "tuning project", so it's like turning an Audi or Mercedes into a better/faster/nicer Audi or Mercedes. But tuning can turn a Audi sedan into a truck. So sadly, it is beyond the scope of the project to correct some fundamental design decision, not to say design mistakes.
