### ISSUE TITLE
[Feature request]: folder sorting

### ISSUE THREAD

**Issue by lgbaldoni** [Betterbird/thunderbird-patches#217]
Hello,
I'm a long-time user of Thunderbird and the Manually sort folders extension, which appears to be suffering from an [intractable problem](https://github.com/protz/Manually-Sort-Folders/issues/199) since release 115.
So, I wondered if you might be interested in upstreaming such a feature in a way that might be more stable.

Regards

**Comment by Betterbird** [comment]
We're not getting involved with Manually sort folders. As far as I can see, it had/has three functions:
1. Sort accounts - No longer needed since this was integrated into TB 91 or 102 (can't remember now)
2. Set a start-up folder. That's already available in BB
3. Sort folders. That's lacking now. Can be achieved by an ugly naming scheme, like "01 top folder", "02 middle folder", "03 bottom folder".
