### ISSUE TITLE
Include .desktop file in linux build tar

### ISSUE THREAD

**Issue by ishanarora** [Betterbird/thunderbird-patches#229]

**Comment by Betterbird** [comment]
The project provides a [.desktop file](https://github.com/Betterbird/thunderbird-patches/blob/main/metadata/eu.betterbird.Betterbird.desktop) which you can tailor to your needs.
We use the Mozilla build tools (`./mach package`) to build the .tar.bz2 and for some reason Mozilla have no provision to include a desktop file. FlatPak and Arch AUR already ship one.

It would be some effort to change our [build script](https://github.com/Betterbird/thunderbird-patches/blob/main/build/build.sh) to include the .desktop file. Since there were no complaints since 2021, this issue doesn't appear to have high priority. Can you submit a PR?

**Comment by Betterbird** [comment]
This is not planned. We have an installation script now which produces a desktop file and adjusts it based on install location. This is more useful than packaging the desktop file.

https://github.com/Betterbird/thunderbird-patches/blob/main/install-on-linux/install-betterbird.sh
