### ISSUE TITLE
can't import thunderbird profile

### ISSUE THREAD

**Issue by dchmelik** [Betterbird/thunderbird-patches#238]
I can't import thunderbird  78.9.1 (last version with movemail) profile.  After 0% it says check error log, which I can't find.  I also couldn't send this on your website's front page because the 'contact' link is broken.

**Comment by Betterbird** [comment]
Which contact link is this exactly? As far as I can see, there's none on the front page. There are others sprinkled around the website and some people contact us, so some of them must be working. It's possible that one particular one isn't.

The import we inherited from upstream TB is broken and will certainly not import movemail. Please refer to:

https://www.betterbird.eu/support/index.html#switch-tb-bb and this section:

Warning: We have had many support cases where things don't work in mysterious ways after using the import function to import a Thunderbird profile. This functionality comes directly from our Thunderbird base and appears to be deficient. So please use with care. It's better to manually copy a Thunderbird profile in the OS if you require a copy in the first place instead of running Betterbird on an existing Thunderbird profile. We're unable to support users who have used the import function.

There is nothing else we can action here, so closing this ticket.

**Comment by dchmelik** [comment]
I still can't copy/import it manually if I don't know where to.
        I meant the support page contact link is broken.

**Comment by Betterbird** [comment]
Both mailto: links on the support page work (you need JS in your 
browser).

The profile location is described on the support page. The documentation 
on how to copy is lacking, fair enough.

Start BB with `-p`, create a new profile with a discernable name. Close 
BB. Remove all content from the new profile folder and copy the existing 
profile folder content.

**Comment by Betterbird** [comment]
We've update the support page adding this:
It's better to manually copy a Thunderbird profile in the OS if you require a copy in the first place instead of running Betterbird on an existing Thunderbird profile. Brief instructions: Run `betterbird -p` to create a new profile taking note of profile name and storage location. After closing Betterbird, replace the content of the newly created profile folder with the content of an existing profile folder.
