### ISSUE TITLE
blank screen after copying Thunderbird profile

### ISSUE THREAD

**Issue by dchmelik** [Betterbird/thunderbird-patches#239]
I followed instructions to create a new profile, then exit, then delete its contents & copy in my Thunderbird profile contents on command-line, then restart Betterbird and open that profile, but then I get a blank screen (no mailboxes, which display fine in Thunderbird) as shown... can I do anything do debug/recover?

![Screenshot_2023-12-18_17-01-13](https://github.com/Betterbird/thunderbird-patches/assets/10347890/5233a6b0-b941-48fc-9e30-304e8d11760c)

You can also see invisible menu colour [Thunderbird bug 1870755](http://bugzilla.mozilla.org/show_bug.cgi?id=1870755) in this screenshot, which I don't know they'll do anything about, as in past they insisted it's a GTK problem when screenshots show all other GTK programs having visible menu with same theme.

**Comment by Betterbird** [comment]
Sorry, but profile management is not a software fault to be reported here, but a support issue. Users copy profiles all the time, we can't diagnose what's gone wrong with your profile.

Make a backup of your existing TB profile and then run BB on it directly.

**Comment by Betterbird** [comment]
Oh, that's the the profile from TB 78? Maybe something went wrong during the profile upgrade, a lot has changed between 78 and 115. You could try running 102 first on the profile. In the end it might be quicker just to use a new profile and copy the Mail folder with the local mail into it.

**Comment by dchmelik** [comment]
Actually this time I ran the profile in Thunderbird 115.5.2 and it worked fine there.

**Comment by Betterbird** [comment]
Yes, TB 115 would have removed the movemail config, not the data itself. It's a bit of a mystery why the profile doesn't start in BB 115 then. Anything in the error console?

**Comment by dchmelik** [comment]
I don't know how to get to error console!

**Comment by Betterbird** [comment]
Look, this is a bug tracker, not a support forum. https://www.betterbird.eu/support/:

Understandably we cannot give user support with account setup, profile management, configuration customisation (incl. developing userChrome.css) or **troubleshooting individual problems**. Since Betterbird and Thunderbird are very similar, users have access to a plethora of online resources, forums and newsgroups to discuss their issues.

All the time we need to spend giving very basic support gets taken away from the development time. First search hit on:
https://www.google.com.au/search?q=thunderbird+error+console:
Open Thunderbird Menu > Tools > Developer Tools > Error Console or hit the hotkeys Ctrl+Shift+J.

**Comment by dchmelik** [comment]
Then document in help menu.  Seems there are one or more bugs: error console shows many warnings/errors (so shouldn't this issue be reopened?).  Originally took more than two screens (and Thunderbird did a bad job by giving no quick way to save error console log to text file) so I wasn't sure I'd be able to report and exited, but then turned a monitor on side to screenshot... second time there wasn't as much log.  Originally had warnings/errors for many addons/extensions/plugins and calendar (which I generally don't use) and I see some about tabs (which I want to disable)... should I not have closed tabs until finished logging?

![Screenshot_2023-12-19_02-56-58](https://github.com/Betterbird/thunderbird-patches/assets/10347890/becd490e-2313-458f-92a2-7ec460f38f57)

**Comment by Betterbird** [comment]
Thanks for the debugging information. The error is here:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/97512d4b-a7fd-432b-8995-7da2b7771936)
There is some profile corruption and a folder doesn't have a corresponding database.

We're catching this case now:
https://github.com/Betterbird/thunderbird-patches/commit/080f3b83cde1191dab8b9020561e6eca7a9d458f
It's a mystery why this would work in TB. Upstream bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1870817
We'll ship the fix in BB 115.6.0-bb21 due for release today.

So what happens is that you are using unified folders or a virtual folder and its database can't be accessed.
You could try the following in any session that will still open the profile:
1. close all tabs
2. switch folder mode to "All Folders"
3. try opening the profile in BB.

If that still doesn't work, please send another screenshot of the error console.

No need to reopen the ticket since it's already fixed ;-)

**Comment by Betterbird** [comment]
It's been release now.

**Comment by Betterbird** [comment]
@dchmelik: So does the new release work? What does the error console say? You can just copy/paste the relevant text.

**Comment by dchmelik** [comment]
Yes: new release works!  However, almost all my addons/extensions/plugins no longer do, so I may use Thunderbird 78.9.1 until stops working.

**Comment by Betterbird** [comment]
Thanks for the feedback. Would have been interesting to see the console output to know which folder caused the issue.

Most important/popular add-ons already work in version 115. Add-ons are a difficult subject. Many are badly programmed and damage the host application. Those which don't work in 115 any more are likely unmaintained anyway.

Older versions of TB are full of exploitable security holes.

**Comment by RealRaven2000** [comment]
> Yes: new release works! However, almost all my addons/extensions/plugins no longer do, so I may use Thunderbird 78.9.1 until stops working.

You should really go the extra mile and check for compatibility, there are loads of compatible Add-ons for Thunderbird 115 - if in doubt, install the compatibility checker Add-on, it will give you a green light when 100% are compatible. Remember we (Add-on developers) had to fork a lot of experimental code to become compatible with the new front end in Tb115. The addons platform - addons.thunderbord.net can only show 1 version as compatible when you look at it from Thunderbird (because it was written for Firefox, who do not care for backwards compatibility  with older versions).

https://addons.thunderbird.net/en-US/thunderbird/addon/addon-compatibility-check/?src=search
