### ISSUE TITLE
Italian language support

### ISSUE THREAD

**Issue by jacopotorrini** [Betterbird/thunderbird-patches#24]
How can I help you for Italian language support?

**Comment by Betterbird** [comment]
Hi there, BB is localised via a script, see https://github.com/Betterbird/thunderbird-patches/tree/main/scripts for examples. Currently we only ship (US) English and German since those are the largest user groups. You can see in which languages TB is used here:
https://stats.thunderbird.net/#platlang: 22% German, 17% English, 14% Japanese, 10% French, 7% Italian, the rest is under 6%. We have partial localisations for Dutch, Hungarian and Chinese, but are not shipping those. There's been a request for Portuguese we haven't followed up on.

As you can see from the scripts directory, basically an `it.cmd` script is required. You can then create a new installer placing that script together with the `repack(-linux).cmd` and the installer into the same directory and executing `repack it 91.5-bb24`. If your language used non-ASCII characters (like accented characters) and you're running the scrip on Windows, you need to set the system locale to UTF-8.

That said, we're not sure which locales would give us the best coverage for the least effort.

**Comment by Betterbird** [comment]
We've just added Japanese :-) - Issue #25.

**Comment by Betterbird** [comment]
We've got French and Spanish now, they could start you off.

**Comment by Betterbird** [comment]
We've just added Portuguese (https://github.com/Betterbird/thunderbird-patches/tree/main/102/scripts), so starting from French, Spanish or Portuguese shouldn't be hard. There are just a few strings.

**Comment by Betterbird** [comment]
OK, someone made a start, perhaps someone can state that the really want to use BB in Italian and revise the enclosed file.
[it.cmd.txt](https://github.com/Betterbird/thunderbird-patches/files/9481225/it.cmd.txt)

**Comment by jacopotorrini** [comment]
> OK, someone made a start, perhaps someone can state that the really want to use BB in Italian and revise the enclosed file. [it.cmd.txt](https://github.com/Betterbird/thunderbird-patches/files/9481225/it.cmd.txt)

I made a revision, I'm very interested in an italian version of betterbird.
[it.cmd.txt](https://github.com/Betterbird/thunderbird-patches/files/9597145/it.cmd.txt)

**Comment by Betterbird** [comment]
Thanks for that, we were waiting for an native Italian speaker to a) revise the translation and b) request the locale.

We'll ship it today or tomorrow in 102.3.0.

One question: Looking at the corrections, your remove "del mouse" here:
New: Fai clic col tasto destro per cancellare la selezione delle singole etichette.
Old: Fai clic con il tasto destro del mouse per cancellare la selezione delle singole etichetta.

Is it clear that "tasto destro" refers to the mouse. I guess so, since no other device does clicks.

**Comment by Betterbird** [comment]
https://www.betterbird.eu/downloads/LanguagePacks/it-102.2.2-bb16.xpi

We've briefly installed it and it look pretty Italian to us 😉 

That works with BB 102.2.2 and the upcoming 102.3.0. If you use the former, please follow https://www.betterbird.eu/expert-tips/ (quote):

Language Packs

As of September 2022 we're shipping language packs for the languages we support. Betterbird language packs are specially made for Betterbird to cover its additional functionality. Thunderbird language packs are not compatible with Betterbird. To take advantage of language switching in the user interface provided in the settings, set the following preferences (will be the default from version 102.3.0): intl.multilingual.enabled - true and intl.multilingual.downloadEnabled - false, the latter to avoid downloading incompatible Thunderbird language packs.

**Comment by jacopotorrini** [comment]
> 

Yes, "del mouse" is redundant.
There are a few other corrections: "con il" is equivalent to "col" but is shorter. "Crittare" is ok but is better and also correct "criptare", it is more "computer style".

**Comment by Betterbird** [comment]
Yes, I saw the other corrections. I speak French and Spanish, I also have a good reading understanding of Italian. BTW, the original translation was a machine translation done by a contributor who wanted to help. I didn't want to ship it without "native" input.

Now the question: for 102.3.0, would you like a localised version for Windows or Linux or will you make do with the language pack?

**Comment by jacopotorrini** [comment]
I've already installed language pack and it works.
By the way I use Linux.
Thank you!

**Comment by Betterbird** [comment]
OK, well, we'll ship Italian for Windows, Linux and as language pack then. We'll see how many downloads we get.

**Comment by Betterbird** [comment]
We've just added some more strings: https://github.com/Betterbird/thunderbird-patches/commit/504107767130c06f903974b534673d3353dc41b3

Could you please check the Italian file. Also, @jacopotorrini, please get in touch via e-mail so we can include you on the localisers mailing list.

**Comment by Betterbird** [comment]
Please get in touch via e-mail. We periodically need more translations, this time for:
Enable vertical tabs (see: https://www.betterbird.eu/media/img/vertical-tabs.png)
Display attachment list above message

**Comment by Betterbird** [comment]
I've done:
Mostra le schede verticalmente
Mostra gli allegati sopra il messaggio

**Comment by jacopotorrini** [comment]
Although not literal, it seems the best translation to convey the concept

-- 



*Jaewa Srl*
 via del Lavoro, 55
 50041 Calenzano, Firenze
 www.jaewa.com 
<http://www.jaewa.com>






La presente e-mail è inviata dall’Impresa 
Jaewa S.r.l. che opera secondo i principi di liceità e trasparenza a tutela 
della riservatezza, delle libertà, della dignità e dei diritti degli 
interessati ai sensi del GDPR 679/16 EU. Il suo contenuto è strettamente 
confidenziale e riservato al destinatario che dovrà trattarne il contenuto 
secondo i medesimi principi. Qualora si ritenga di aver ricevuto 
erroneamente la presente comunicazione, Vi invitiamo a darcene pronta 
comunicazione all’indirizzo ***@***.*** ***@***.***> e a 
provvedere alla distruzione del suo contenuto. Informativa privacy e 
privacy policy aziendale sono consultabili presso le apposite sezioni del 
sito web aziendale www.jaewa.com <http://www.jaewa.com>

**Comment by Betterbird** [comment]
@jacopotorrini : Please get in touch via e-mail. We need more translations for the next release.
