### ISSUE TITLE
Make threads actually useful

### ISSUE THREAD

**Issue by rommeswi** [Betterbird/thunderbird-patches#245]
The title is perhaps a bit polemic. What I mean is that threads are currently not useable because they require too many clicks to see new messages. After clicking on a thread, the message frame shows the list of emails in the thread. It requires again to click onto the sender's address to actually see an email. Worse, if one double clicks the thread, instead of expanding it, the thread opens in another tab.

Several bugzilla issues substantiate that I [am](https://bugzilla.mozilla.org/show_bug.cgi?id=284336) [not](https://bugzilla.mozilla.org/show_bug.cgi?id=305741) [alone](https://bugzilla.mozilla.org/show_bug.cgi?id=218935) with this opinion.

Reddit [also](https://www.reddit.com/r/Thunderbird/comments/16nmcwf/is_there_a_way_to_have_an_email_chain_auto/) [thinks](https://www.reddit.com/r/Thunderbird/comments/u1ejo1/automatically_expand_all_threads/) [so](https://www.reddit.com/r/Thunderbird/comments/wqqffm/sort_by_threaded_but_new_messages_are_hidden_in/).

I don't have a strong opinion on how these issues should be addressed. There are many suggestions in the links above. I would be grateful for anything that gets me to the newest email in a thread with one click in the message/thread list.

**Comment by Betterbird** [comment]
You want polemic? OK, don't use threading, it sucks 😉. 

At least this reference isn't right:
https://www.reddit.com/r/Thunderbird/comments/u1ejo1/automatically_expand_all_threads/
If you expand a folder with `*`, it stays that way. Also (quote): _Worse is I've missed emails because they arrive, are put into an un-expanded thread, and the "root" or "top level" email of the thread shows as read so I ignore it._ Well, threads with new unread messages are at least underlined.

Here's a summary of the others:
https://bugzilla.mozilla.org/show_bug.cgi?id=284336 - "Expand All Threads with Unread" / "Collapse All Threads without Unread"
https://bugzilla.mozilla.org/show_bug.cgi?id=305741 - reversed threading - Issue #160 
https://bugzilla.mozilla.org/show_bug.cgi?id=218935 - scroll to new message - Isn't that implemented now?

https://www.reddit.com/r/Thunderbird/comments/16nmcwf/is_there_a_way_to_have_an_email_chain_auto/ - Auto expand on new message
https://www.reddit.com/r/Thunderbird/comments/wqqffm/sort_by_threaded_but_new_messages_are_hidden_in/ - the same.

We'll see what we can do.

**Comment by Betterbird** [comment]
OK, we got a big of feedback. In general, you can press the letter "n" to advance to the next unread message.

Are you aware of "View > Threads > Threads with Unread"? That will cover part of bug 284336 - "Expand All Threads with Unread".

Bug 218935 - scroll to new message: It will only scroll to new messages when you open a folder, not when you're already in it and new mail arrived. That would also be pretty disruptive. You're looking at some older messages, new mail arrives and the whole thing scrolls away.

There's also https://bugzilla.mozilla.org/show_bug.cgi?id=242300 - New messages in thread are not obvious enough.

I guess the Reddit posts "Auto expand on new message" or the reverse threading would improve the situation.

**Comment by Gunther-Schulz** [comment]
The most obvious (and easiest?) solution to me would be for the order messages inside a thread to adhere to the sorting chosen. I always select date newest, but the thread itself will always be from newest to oldest. Have been missing messages because of that.

**Comment by Betterbird** [comment]
Yes, that's "reverse sorting", Issue #160. We should look into that.

**Comment by Betterbird** [comment]
We've implemented "reversed threading" and we've just fixed an ancient bug that new mail in collapsed threads can't be found easily (https://bugzilla.mozilla.org/show_bug.cgi?id=242300). That will be released in forthcoming versions, Windows build based on 115 here:
https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.15.0-bb32-latest-build5.en-US.win64.installer.exe

https://github.com/Betterbird/thunderbird-patches/commit/2bf03114e65acb7a17b4bf317759e85ff7343725
https://github.com/Betterbird/thunderbird-patches/commit/7c242196a7b15def037103cbffa6a2b92d8fc2aa

Please file a new issue for further suggestions.

**Comment by Betterbird** [comment]
Reversed threading now shows the most recent message as collapsed root:
https://www.betterbird.eu/downloads/get.php?os=win&lang=en-US&version=latest
