### ISSUE TITLE
[enhancement] optionally view address book contacts as photo gallery (TB bug #1456645)

### ISSUE THREAD

**Issue by chrizilla** [Betterbird/thunderbird-patches#247]
### enhancement idea 💡:

view address book contacts as photo gallery
This is a nice feature of modern email clients, but regretfully missing in Thunderbird.

### rationale for adoption in Betterbird:
With such a killer feature, a huge amount of users would migrate from Thunderbird to Betterbird!

### previous requests:
* 6 years ago for Thunderbird: https://bugzilla.mozilla.org/show_bug.cgi?id=1456645
* 6 years ago for Thunderbird's CardBook addon: https://gitlab.com/CardBook/CardBook/-/issues/364

### conceptual screenshot:

![photo gallery (conceptual screenshot)](https://github.com/Betterbird/thunderbird-patches/assets/43895159/832e0c30-2541-4575-bb48-281790e1d5b5)

**Comment by Betterbird** [comment]
> view address book contacts as photo gallery

This request is a little over-zealous. At best, we would supply an AB "photo gallery" view. A gallery would be fun if you had less than - say - 50 contacts, otherwise you'd be spending a lot of time with scrolling.

Under the assumption that most users will have more than 50 contacts and that they don't necessarily maintain the AB to include photos, this feature would not receive a lot of usage. Besides, TB and BB's target audience is not the group of under 26 y/o, which would have such a nice gallery. Do you think you would have pictures for your lawyer, tax agent, landlord, doctor, ... or the plumber (maybe a big wrench)?

BB is a soft fork of TB, that means, that we need to maintain a set of patches, currently about 200 of them, to turn TB into BB at every version we release. We try to keep the footprint of the patches as small as possible, focussing on functional improvements and bug fixes rather than UI changes or changes that require new strings (and hence translations).

I can't see this being implemented, unless of course the TB folks implement it one day.

**Comment by Betterbird** [comment]
Well, we don't have data on user behaviour, so we need to use second guessing.

It's unlikely that someone will scroll through 100+ or 1000+ (mostly non-populated) pictures to find someone. The likeliest access is via text search.

In a survey we conducted in early 2023, nothing related to photos or AB was requested.

**Comment by Betterbird** [comment]
It's not much fun discussing closed tickets (and you're not doing yourself a favour for getting this implemented). The correct quote is: This request is a little **over-zealous**. **At best**, we would supply an AB "photo gallery" view.

That refers to the original request: "view address book contacts as photo gallery" without the word "optionally". So your request was **precisely** to dump the current view and replace it with a photo gallery.

"At best" describes the best possible outcome, however, for reasons given further down in that comment, we decided not to consider this enhancement.

**Comment by Betterbird** [comment]
Oh, yes, they are the perfect spin doctors, "awesome idea", and no action in four years.

Look, TB and BB are open source. Implement it yourself or pay someone to implement it. Submit the patch to TB and get it integrated into TB.

**Comment by Betterbird** [comment]
> What language would I have to learn for the photo gallery ?

JavaScript.

You can browse the code here: https://searchfox.org/comm-central/source/mailnews/addrbook

The TB beginners guide is here: https://developer.thunderbird.net/thunderbird-development/getting-started

**Comment by Betterbird** [comment]
Yes. There are various aspects to the task: You need to get the addresses from the AB and create a HTML page from them. More difficult is to wire this view into the UI which currently supports list and table layout. You can add your business card layout:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/c55bdbd6-572a-4595-9ba1-b97f09c733eb)

But hey, the "awesome" cheerleaders @ TB should do the mentoring.

**Comment by Betterbird** [comment]
Off topic:
> With such a killer feature, a huge amount of users would migrate from Thunderbird to Betterbird!

How about "More Layouts" already in BB. Is that also a killer feature? Apparently so, see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=304697#c7).
