### ISSUE TITLE
Japanese language pack for Betterbird 91

### ISSUE THREAD

**Issue by kiki-ja** [Betterbird/thunderbird-patches#25]
I have created a Japanese language pack for Betterbird from the Japanese language pack for Thunderbird.
The supported versions are for 91.0-91.*.
Please use it if you like.

[japanese_ja_language_pack-91.0buildid20220105-bb.zip](https://github.com/Betterbird/thunderbird-patches/files/7854664/japanese_ja_language_pack-91.0buildid20220105-bb.zip)

![Betterbird 91 5 0-bb24 について](https://user-images.githubusercontent.com/80428201/149143997-c2e588d4-f003-4772-99fb-d038ca2dd23d.jpg)

**Comment by Betterbird** [comment]
Wow, that's great. That gives us coverage for Japan which has the third largest user group, see:
https://stats.thunderbird.net/#platlang - about 15%.

Would you be able to create a script `ja.cmd` like the others we have here:
https://github.com/Betterbird/thunderbird-patches/tree/main/scripts
Maybe take a look at the German `de.cmd` to see all the new strings BB has introduced and also the fixes it needed to make.
Of course we could pull the strings out from the language pack you provided.

We've installed the language pack, which is a bit difficult since Betterbird has the international UI disabled via pref intl.multilingual.enabled, so you need to set that back to true before you can enable the language pack. Or is there another trick?

With your language pack installed, we see this in the error console:
[fluent] Missing translations in ja: add-web-search-engine, type-column-header, action-column-header

Again, please take a look at `de.cmd` to see what's going on with those strings. You can see the effect of the missing strings here:
![image](https://user-images.githubusercontent.com/86832723/149198044-ec118fa0-728e-40e0-81df-4f2ab5456662.png)
and here:
![image](https://user-images.githubusercontent.com/86832723/149198187-3b2652fa-ca7c-4ddc-a014-385fed50fefb.png)
It falls back to the English strings.
The search provider strings have been translated
https://searchfox.org/l10n/rev/79e72f766f756c21464191701cfd328eb7277316/ja/mail/messenger/preferences/preferences.ftl#121
but the ja language pack doesn't have them yet.
The same is true for the other two:
https://searchfox.org/l10n/rev/79e72f766f756c21464191701cfd328eb7277316/ja/mail/messenger/preferences/preferences.ftl#322

**Comment by Betterbird** [comment]
Fixed via https://github.com/Betterbird/thunderbird-patches/commit/61b2c6e7608b32a7ad464161951be6ecb6dd0b9c.

We had to "translate" these two ourselves:
https://github.com/Betterbird/thunderbird-patches/blob/61b2c6e7608b32a7ad464161951be6ecb6dd0b9c/scripts/ja.cmd#L9
https://github.com/Betterbird/thunderbird-patches/blob/61b2c6e7608b32a7ad464161951be6ecb6dd0b9c/scripts/ja.cmd#L10
Please check them and also check the rest of the file.

Also please try the Japanese localised version from https://www.betterbird.eu/downloads/.

**Comment by kiki-ja** [comment]
@Betterbird 

I would like to thank you for your quick response.

１．I am not able to create the ja.cmd script.
2. I need to change "intl.multilingual.enabled = true" to install the Japanese pack.
3. I have fixed add-web-search-engine, type-column-header, action-column-header, etc. as pointed out.

I will upload the modified Japanese language pack below.

[japanese_ja_language_pack-91.0buildid20220113-bb.zip](https://github.com/Betterbird/thunderbird-patches/files/7857576/japanese_ja_language_pack-91.0buildid20220113-bb.zip)

And thank you for build the Japanese version of Betterbird so quickly.

**Comment by Betterbird** [comment]
> I am not able to create the ja.cmd script.

But please check ours: https://github.com/Betterbird/thunderbird-patches/blob/main/scripts/ja.cmd

Please understand that we don't intend to support language packs in Betterbird, there would just be too much confusion with Thunderbird's own language pack and we don't want to host them.

**Comment by kiki-ja** [comment]
@Betterbird

> But please check ours: https://github.com/Betterbird/thunderbird-patches/blob/main/scripts/ja.cmd

Thank you for this.
Yes, I've already checked.
However, I don't understand the script and can't use or create it.

> Please understand that we don't intend to support language packs in Betterbird, there would just be too much confusion with Thunderbird's own language pack and we don't want to host them.

I understand.
I hope that my Japanese language pack will be useful to you.

**Comment by Betterbird** [comment]
Well, the script adds the strings we need for Betterbird to an unpacked language pack.

Did you fix this error you had in your language pack?
<!ENTITY quickFilterBar.tagged.tooltip "1つまたは複数のタグを持つメッセージを表示します。右クリックで個々のタグの選択を解除します。">
The "1" after the quote isn't right, is it?

**Comment by kiki-ja** [comment]
@Betterbird

> Did you fix this error you had in your language pack?
> <!ENTITY quickFilterBar.tagged.tooltip "1つまたは複数のタグを持つメッセージを表示します。右クリックで個々のタグの選択を解除します。">
> The "1" after the quote isn't right, is it?

Thank you very much for pointing this out.
That's right.

The first language pack I uploaded (my Japanese language pack buildid20220105) was missing "1", which has already been fixed in the next language pack (my Japanese language pack buildid20220113).
So, please fix ja.cmd as well.

[ja.cmd]
---- Before ----
%lecho% "<!ENTITY quickFilterBar.tagged.tooltip \"つまたは複数のタグを持つメッセージを表示します。右クリックで個々のタグの選択を解除します。\">" >> chrome\ja\locale\ja\messenger\quickFilterBar.dtd

---- After ----
%lecho% "<!ENTITY quickFilterBar.tagged.tooltip \"１つまたは複数のタグを持つメッセージを表示します。右クリックで個々のタグの選択を解除します。\">" >> chrome\ja\locale\ja\messenger\quickFilterBar.dtd

**Comment by Betterbird** [comment]
Sorry, I'm confused now: You want me to add the "1"? What is that for in Japanese? I translated
つまたは複数のタグを持つメッセージを表示します。右クリックで個々のタグの選択を解除します。
in Google and it comes out as
Display messages with one or more tags. Right-click to deselect individual tags.

**Comment by kiki-ja** [comment]
@Betterbird 

I'm sorry I confused you.

> You want me to add the "1"?

Yes, that's correct. **Please add "1".**

> What is that for in Japanese?

**Example:**
en-US = ja
one = １つ
or = または
more = 複数

![DeepL Translate Example](https://user-images.githubusercontent.com/80428201/149411718-269ebdfc-b2fb-4ff8-9b96-afea9f9bd399.png)
DeepL Translate: The world's most accurate translator
https://www.deepl.com/translator

**Comment by Betterbird** [comment]
Done, https://github.com/Betterbird/thunderbird-patches/commit/95cb2619b06fd56674463ec7202a75f4fb7f4840.
Thanks for your help.

**Comment by Betterbird** [comment]
@kiki-ja: Can ypu please help with a translation for:
https://github.com/Betterbird/thunderbird-patches/blob/365ac5ba07f79ba33c738cfd1aa6e64c85389abf/91/bugs/297852-grouping-search-term.patch#L95

That's the tooltip for the new `+( )` button: https://www.betterbird.eu/media/img/complex-search-terms.png

Would you mind getting in touch via e-mail (betterbird@betterbird.eu)?

**Comment by kiki-ja** [comment]
I have added the Japanese translation.
Please replace it with the attached file.

[en-US] groupButtonTooltipText=Add a new group
[ja] groupButtonTooltipText=新しいグループを追加します

@kiki-ja
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# these are the fields that get inserted in the search line
# for "and" searches, this looks like:
#
# searchAnd0 <attribute> searchAnd1 <operator> searchAnd2 <value> searchAnd4
#
# for example, in english this looks like:
# and the [Sender ] [doesn't contain] [John]
#
# TODO: need to special-case the first line (filterindex==0)

# filter stuff

searchingMessage		= 検索しています...
# LOCALIZATION NOTE (matchesFound): #1 number of matches found
matchesFound			=#1 件見つかりました
noMatchesFound		= 見つかりませんでした
labelForStopButton		= 停止
labelForSearchButton		= 検索
labelForStopButton.accesskey	= S
labelForSearchButton.accesskey	= S

moreButtonTooltipText		= 新しいルールを追加します
groupButtonTooltipText		= 新しいグループを追加します
lessButtonTooltipText		= このルールを削除します
