### ISSUE TITLE
Tag list in "Settings" not updating after adding/editing/deleting tags

### ISSUE THREAD

**Issue by Gary92** [Betterbird/thunderbird-patches#250]
The title says it all. In the "Tags" section of the "General" menu in "Settings", any changes applied to the tags are not reflected in the list, which instead remains the same. To see the updated list, the "Settings" tab must be closed and reopened. I tried uninstalling/reinstalling the application, without success. I also tried on Thunderbird and I did not encounter the problem there.

v115.6.1-bb22 (64 bit), Windows 11 23H2

**Comment by Betterbird** [comment]
Confirmed, one of the rare cases of "works in TB, doesn't work in BB". We'll look into it.

**Comment by Betterbird** [comment]
The cause was an upstream issue, https://bugzilla.mozilla.org/show_bug.cgi?id=1874557, which would also be visible on Linux distributions which build TB without automatic updates. We've fixed it, the fix will ship in the next version 115.7.0-bb23 on the 23rd of January and soon in the next 115.6.1-bb22 "latest build" which we do in English for Windows and Linux. Which platform are you on?

**Comment by Betterbird** [comment]
https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.6.1-bb22-latest-build6.en-US.win64.installer.exe

**Comment by Gary92** [comment]
> The cause was an upstream issue, https://bugzilla.mozilla.org/show_bug.cgi?id=1874557, which would also be visible on Linux distributions which build TB without automatic updates. We've fixed it, the fix will ship in the next version 115.7.0-bb23 on the 23rd of January and soon in the next 115.6.1-bb22 "latest build" which we do in English for Windows and Linux. Which platform are you on?

Understood, I'm glad the bug was fixed so quickly (despite it being the weekend), congratulations.
By the way, I'm on Windows 11 23H2, I've just installed the latest build you provided and I confirm that the bug has gone. 👍

**Comment by Betterbird** [comment]
As we wrote, the "works in TB, doesn't work in BB" is really "works in TB if build with automatic updates, doesn't work in TB if build without automatic updates".

BB and all TBs compiled by Linux distros fall into the second category, so it's actually quite a nasty bug caused by a careless code change by the TB folks.

Glad you could make use of the latest build for Windows.
