### ISSUE TITLE
Portable Betterbird version throws an error on start

### ISSUE THREAD

**Issue by HyperCriSiS** [Betterbird/thunderbird-patches#258]
Hi,

I just wanted to test Betterbird for the first time.
After starting the portable german version I get this error
![betterbird_EklinbWYcj](https://github.com/Betterbird/thunderbird-patches/assets/11708192/bccf3b24-dbc8-41ca-99ca-9dfb34c33a10)

It still starts and looks like this:
![betterbird_k3qtLnYV1B](https://github.com/Betterbird/thunderbird-patches/assets/11708192/09ebd30e-6ef0-4d3e-b968-44e5be83fbeb)

Regards
Hyper

**Comment by Betterbird** [comment]
This seems more like a support issue rather than a software fault.
It's not clear what is causing this error, maybe some antivirus program is interfering.

Yes, when you first start it, you're prompted to create and account, second tab: "Konto einrichten". If you don't do that, you get an empty screen. You can of course copy an existing Thunderbird profile into the portable profile.

**Comment by HyperCriSiS** [comment]
I only have the Windows defender running. No other Anti-Virus Software. 
How can I provide a debug log?

**Comment by Betterbird** [comment]
There is no logging at that level. Somehow the error description looks familiar, but I can't remember where I've seen it. It must be something in your environment. Try unpacking it to a different location or different machine. Or ask on a forum like this one:
https://www.thunderbird-mail.de/forum/board/91-betterbird/
