### ISSUE TITLE
Feature request: Set notifications per each account/folder (as the old "Mailbox alert" extension did)

### ISSUE THREAD

**Issue by ElimGarak72** [Betterbird/thunderbird-patches#260]
Hello!
What I would really love (and need) to see in Betterbird is what the old "Mailbox Alert" extension did, which is now long unsupported.
https://addons.thunderbird.net/en-US/thunderbird/addon/mailbox-alert/

Basically, it allowed the user to set a personalized alert for each time every different account/folder got a new message (or none at all).
This is particularly useful to me, because I have several mail accounts and I would like to play a different sound for each one of them.
Also, I would like to NOT receive any notification at allo from a couple of these accounts.

Thank you!

**Comment by Betterbird** [comment]
Someone should fix https://addons.thunderbird.net/en-US/thunderbird/addon/mailbox-alert/. We can't integrate functionality from all no-longer-supported add-ons.

BB is a soft fork of TB, that means, that we need to maintain a set of patches, currently about 200 of them, to turn TB into BB at every version we release. We try to keep the footprint of the patches as small as possible, focussing on functional improvements and bug fixes rather than UI changes or changes that require new strings (and hence translations).

The cost-benefit ratio for this proposal isn't convincing.
