### ISSUE TITLE
Multiple spellcheck dictionaries don't remain active across multiple messages

### ISSUE THREAD

**Issue by jmrohwer** [Betterbird/thunderbird-patches#269]
I frequently compose emails in different languages and have multiple dictionaries installed. In TB I have multiple dictionaries activated simultaneously so I don't have to switch languages all the time when composing new messages. The active dictionary selection "sticks" until I change it, across multiple messages. This has worked fine for a long time.

In Betterbird, I can also activate multiple languages at the same time as well. However, whenever I compose a new message, only the default language (English UK in my case) is enabled and I have to re-enable the other languages again (Compose window -> right click in message text area -> Languages).

While I really like other features of BB, this is a deal breaker for me and renders BB unusable as daily email driver.

Tested on my regular TB profile as well as a new profile created with BB.

Betterbird 115.7.0-bb23
Thunderbird 115.7.0
Manjaro Linux

**Comment by Betterbird** [comment]
This doesn't sound right. In fact, TB is broken and multiple dictionaries do **not** work reliably, they are finally fixing this in https://bugzilla.mozilla.org/show_bug.cgi?id=1790746. They've collected 7 duplicates over the two years after the release of the feature. This bug is fixed in BB since version 102.

When I start a new message, I get this:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/5aa3ef3e-b88f-4d50-8343-2ec01bd36fd4)


I know it works since I use it all the time.

Messages are generally independent, so settings in one message don't carry over to other messages, that it, you can write one message in English and another one in German and another one in Spanish, all open at the same time.

We'd like to understand what you're reporting exactly. What's the "active dictionary selection", and why is there a need to change it if you enabled all the languages that you use?

**Comment by jmrohwer** [comment]
Thanks, it works now after activating the dictionaries in Settings->Composition->Spelling. Then it is also persistent across messages. I'm closing the issue, sorry for the noise!

The question remains why the settings were not pulled through from my TB profile, as BB and TB should be able to use the same profile? I should add though that spell checking on TB on Arch/Manjaro can work via hunspell and I had only system-installed dictionaries, no user extensions/addons. On BB I had to install the dictionaries as add-ons. Maybe that has something to do with it. Either way, it works now. Thanks for the help!

**Comment by Betterbird** [comment]
Thanks for getting back. Linux is a can of worms and I've never heard about _"TB on Arch/Manjaro can work via hunspell and I had only system-installed dictionaries"_. We'd have to investigate how that works. Maybe TB ships with a set of dictionaries whereas BB doesn't.

**Comment by jmrohwer** [comment]
Upon installation the package creates a symlink `/usr/lib/thunderbird/dictionaries -> /usr/share/hunspell` and has dependencies for hunspell and hunspell-en_US. Further hunspell dictionary packages can be installed to provide additional languages, and these are then automatically recognised by TB. The dictionaries are not shipped by TB. This has to do with Arch Linux packaging.

**Comment by Betterbird** [comment]
Looks like you comments at
https://aur.archlinux.org/packages/betterbird-bin#comment-957013
were incorporated here:
https://aur.archlinux.org/cgit/aur.git/commit/?h=betterbird-bin&id=1c7b1341b7ae5c049e5c22a1210f5094b5d1356a
https://aur.archlinux.org/cgit/aur.git/commit/?h=betterbird-bin&id=efe62118e595d5966da3cf41ad151ed332e1f9e8

Can you please confirm that this works as desired now.

**Comment by jmrohwer** [comment]
All good, thanks!
