### ISSUE TITLE
Global Search - Sort by date has wrong order (Asc insted of Desc) in list view

### ISSUE THREAD

**Issue by Hakun1n** [Betterbird/thunderbird-patches#288]
Hi team!

List view of Global search results sorts from oldest (top) to latest (bottom).
Seems like the view tries to focus on the latest email as it opens at the bottom of the list (since the sort is Asc) but then it scrolls all the way up on its own.

Note: Faceted search order is correct (By date, Desc)

Thunderbird 115 works as expected -> The list view sorts by date with most-recent on top (Descending sort)

Betterbird version: 115.9.0-bb26

**Comment by Betterbird** [comment]
Did you get the "build2"? There was a scrolling issue in the first build.

**Comment by Hakun1n** [comment]
I assume YES as I got `betterbird-115.9.0-bb26-build2.en-US.win64.installer.exe`

And wow for the nearly-instant response O_o

**Comment by Betterbird** [comment]
Hmm, then it will take longer to setup and check. We don't use Gloda much and this is the first report about this.

**Comment by Hakun1n** [comment]
No problem. Let me know if you need more details, logs/debug or something...

BTW: I'd rather not use it at all but sometimes i HAVE to ... see my other post/request :D

**Comment by Betterbird** [comment]
OK. So the issue is that TB had a bug which was fixed. The Gloda list in TB is always descending not paying attention to mailnews.default_sort_order. This was fixed here https://hg.mozilla.org/comm-central/rev/17239bec4e1c#l3.12, but the fix is not in TB 115 yet, it **is**  in BB 115. The result is that BB will pay attention to the pref whose default is 1, ascending.

If you don't like the behaviour, set the pref to 2, descending and Gloda will pay attention after a restart.
