### ISSUE TITLE
Add email as reminder of events in TB/BB calendar (enhancement)

### ISSUE THREAD

**Issue by topoldo** [Betterbird/thunderbird-patches#292]
I would like if TB/BB have the possibility to remind calendar event(s) with an email beside to the alarm.
At the moment you can get this behavior only by configuring the event in a network calendar (for example Google calendar) which supports also this kind of reminders.
In this case, of course, no icon recalling that a certain event will be notified (also) this way is present in TB/BB, at difference with some previous versions of TB+Lightning which allowed emails as a reminder.
At the URL:
https://connect.mozilla.org/t5/ideas/thunderbird-lightning-before-event-starts-automatically-send/idi-p/36808
you can find a request for this feature in TB but the thread was archived :-(

**Comment by Betterbird** [comment]
We will likely not address this. As per this post, the TB folks may rewrite (some of) their calendar code at some stage:

https://thunderbird.topicbox.com/groups/planning/T537fbacf7567bae6-Mc28c632e7e0eb1f421cfdfc2 (quote):

Calendar rebuild

Another very large initiative we’re kicking off during this new ESR cycle is a complete rebuild of our Calendar.

Not only are we going to clean up and improve our back-end code handling protocols and synchronization, but we’re also taking a hard look at our UI and UX, in order to provide a more flexible and intuitive experience, reducing the amount of dialogs, and implementing those features that users have come to expect from any calendaring application.
