### ISSUE TITLE
Highlight (leave highlighted) the email in the list when you click on the email message to read it.

### ISSUE THREAD

**Issue by denglish77** [Betterbird/thunderbird-patches#316]
Like so: 
![Highlighted email in Betterbird](https://github.com/Betterbird/thunderbird-patches/assets/174129953/c2aaa86f-5ac3-4c81-8907-7fe586c83702)

**Comment by Betterbird** [comment]
Sorry, this is incomplete. Which version, which OS?

Of course the selected e-mail is highlighted:
![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/2c33011e-353c-4eea-8d0d-c3a5cb097ac0)

**Comment by denglish77** [comment]
I was not talking about the email id info being highlighted when you click on it. It always does. BUT when you click on the message pane in the Vertical view layout  with Folder Pane , Message List Header, and Message Pane, the highlighting of the Message Header un-highlights making it difficult to find where you were in the list of emails.

David English

**Comment by Betterbird** [comment]
When the message list loses focus, the selection is shown differently, that's correct and intentional:

![image](https://github.com/Betterbird/thunderbird-patches/assets/86832723/034dd57b-b062-448b-9b72-46949a02b91c)

You can add something to userChrome.css to make the selected message stand out more when the message list has lost focus.
