### ISSUE TITLE
feature-689067-disable-account.patch  fails to apply

### ISSUE THREAD

**Issue by chris2553** [Betterbird/thunderbird-patches#322]
As said in the title, patch feature-689067-disable-account.patch fails to apply.
The output on the console end with:
applying feature-689067-disable-account.patch
patching file mailnews/base/prefs/content/am-server.xhtml
Hunk #2 FAILED at 285
1 out of 2 hunks FAILED -- saving rejects to file mailnews/base/prefs/content/am-server.xhtml.rej
patch failed, unable to continue (try -v)
patch failed, rejects left in working directory
errors during apply, please fix and qrefresh feature-689067-disable-account.patch

mozilla-esr128/comm/mailnews/base/prefs/content/am-server.xhtml.rej contains:
--- am-server.xhtml
+++ am-server.xhtml
@@ -285,8 +286,19 @@
               accesskey="&downloadOnBiff.accesskey;"
               prefstring="mail.server.%serverkey%.download_on_biff"
             />
           </vbox>
+          <vbox align="start">
+            <checkbox
+              hidefor="movemail,nntp"
+              wsm_persist="true"
+              id="server.disabled"
+              data-l10n-id="account-disabled"
+              oncommand="onAccountDisabled();"
+              prefattribute="value"
+              prefstring="mail.server.%serverkey%.disabled"
+            />
+          </vbox>
           
           <vbox align="start" hidefor="movemail,imap,nntp">
             <checkbox
               wsm_persist="true"

I've never used mercurial, so if you need any additional diagnostics, I'll almost certainly need help.

**Comment by Betterbird** [comment]
Yes, that fails to apply since it depends on the movemail patch which isn't published.

For the time being, edit the patch, which is the last in the queue and replace
`<vbox align="start" hidefor="movemail,imap,nntp">` with `<vbox align="start" hidefor="imap,nntp">`.

Or replace feature-1802145-reestablish-movemail.patch of which we'll push a modified version in a minute.

**Comment by Betterbird** [comment]
This should work, if not, please let us know.

What are you building this for?

**Comment by chris2553** [comment]
On 13/07/2024 23:13, Betterbird wrote:
> This should work, if not, please let us know.
>

Thanks for the patch, which fixes the problem.

> What are you building this for?
> 

I've used linux-based systems for my home computing for many years. When I retired I decided I wanted to understand more
about how a linux-based system hangs together. So in 2015 I built my own system from ground up using the Linux From
Scratch recipes. I now have a system (which I call krisux) that exactly matches the things I use my laptop for. I update
most packages as new versions are released so I guess you could say I have a rolling release (and a user base of 1.)
With only a few exceptions, all my software is built from source.

One thing I have found is that the larger, more complex applications are most likely to throw build problems - no
surprises there. So I tend to grab snapshots every so often during the development and try to build them on my system.
That means I get to pick the problems off one or two at a time rather than a whole bundle at release time. I usually
report a problem that I find (and, if I have one, my solution) to the project. I should say that on the whole, problems
are few which shows the high quality of the large majority open source software and its developers.

This is the first hitch I've run into since I started looking at Betterbird. I've been using BB-128 for email and
calendar for a couple of weeks now and it's been absolutely fine.

**Comment by Betterbird** [comment]
Thanks for testing and thanks for the information. All the versions with a tag in the repo will build, since other people build it, too. When adding feature-689067-disable-account.patch, we were aware that the other patch needed an adjustment, and then, the issue "slipped off the desk", apologies!

In the future, you can also get in contact via e-mail. We've also build 128 for Linux bug haven't published it since it's an older build than the published Windows build.
