### ISSUE TITLE
Code Signing installers take 2

### ISSUE THREAD

**Issue by f3rrix** [Betterbird/thunderbird-patches#345]
Per #67 it was indicated that installers were authenticode signed by a self-signed cert.  Did this process stop or break? Because Windows does not show any digital signature on the downloads.  

(Even though it shouldn't matter for this part, I did install the root cert trust to prove that didn't make a difference.  it's not showing untrusted, rather completely unsigned)

Aside about certs and cost: My small company is looking for a TB replacement that is more performant for very large IMAP folders.  If it works for us, we would be happy to sponsor the cost of you obtaining and maintaining code signing certs.  In fact we would probably be able to pay toward supporting performance improvement if needed.

**Comment by Betterbird** [comment]
The certificate expired. Please install the new one:
https://www.betterbird.eu/downloads/WindowsSigningCertificate/betterbird-signing%20(caution-install%20into%20trusted%20root%20CA)%20expires%20July%202027.cer

It works here:
![image](https://github.com/user-attachments/assets/f2c24b88-f722-4ae0-9fc6-328852aeb79d)

The issue with obtaining a signing certificate is the price on one side, but also that it would be issued for the project leader and not the project itself, since the project is not a "legal entity" yet.

Re. IMAP: No difference between TB and BB here.

**Comment by f3rrix** [comment]
Thanks for all the info!
