### ISSUE TITLE
Application Error on Betterbird Startup in Windows 11

### ISSUE THREAD

**Issue by bannert1337** [Betterbird/thunderbird-patches#346]
When starting Betterbird (version 115.15.0-bb32 64-bit) on Windows 11, an Application Error dialog appears, halting the startup process until acknowledged. The error message reads:

![csrss_OsOMyFcEtQ](https://github.com/user-attachments/assets/6ab41717-2e08-4d84-aea7-d99a8bfe1e93)
"The instruction at 0x00007FFC358D49F0 referenced memory at 0x0000000000001240. The memory could not be read."

Despite this error, Betterbird appears to function normally after clicking "OK" to dismiss the dialog.

System Information:
- OS: Windows 11 Pro, Version 23H2
- OS Build: 22631.4037
- Processor: AMD Ryzen 7 5800X3D 8-Core Processor 3.40 GHz
- RAM: 64.0 GB
- System Type: 64-bit operating system, x64-based processor

Additional Notes:
- The Atlas Playbook has been used on this Windows installation.
- The error occurs consistently on startup.
- No other issues have been noticed after dismissing the error dialog.

Steps to Reproduce:
1. Install Betterbird 115.15.0-bb32 (64-bit) on Windows 11 Pro (Version 23H2)
2. Launch Betterbird
3. Observe the Application Error dialog

Expected Behavior:
Betterbird should start without any error dialogs.

Actual Behavior:
An Application Error dialog appears, requiring user interaction to proceed.

Please investigate the cause of this startup error and provide any potential solutions or workarounds. Let me know if you need any additional information or logs to assist with troubleshooting.

**Comment by Betterbird** [comment]
> Please investigate the cause of this startup error and provide any potential solutions or workarounds.

How exactly would we "investigate the cause of this startup error"?

Some general advice:
1. (Make sure BB is correctly installed.)
2. (Make sure there are no hardware errors or issues with your OS installation.)
3. Disable your anti-virus software or exclude the betterbird.exe executable and related DDLs from the anti-virus scan.
4. Start Windows in safe mode.
5. Try a different Windows computer.
6. Try starting BB on a different or new profile (use `-p` option to start).

Sorry, these errors are as frustrating for the user as they are for the software provider since there is no clear answer and the problem is not with the supplied software but with the user's PC.
