### ISSUE TITLE
Notifications always popping up on non-primary monitor

### ISSUE THREAD

**Issue by konstanzzz** [Betterbird/thunderbird-patches#348]
[Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=637830)

Betterbird 115 (Flatpak)

All notifications appear on my second monitor regardless of which monitor I have Betterbird on. It also happens even when BB is minimized to tray.

My _"Use the system notification"_ setting is turned off.

Ideally I'd like to have the notifications appear on my primary monitor. This is kind of fixed by using system notifications instead, but the problem with that is clicking on the notif won't immediately show me the new email. It won't even open BB at all.

Can this be fixed in Betterbird? It's been more than a decade and this bug still exists.

Thanks.

**Comment by Betterbird** [comment]
This is tricky since we're mostly a Windows project. The TB/BB-native (non system) notifications are shown where the system tray is, that's usually the primary screen. It may also differ between Linux desktops.

In https://bugzilla.mozilla.org/show_bug.cgi?id=637830#c13 Magnus was likely referring to this line:
https://searchfox.org/comm-esr78/rev/ba95b27c546ce348adadd41ce57d2a944df198ad/mailnews/base/src/nsMessengerUnixIntegration.cpp#369,
however that code is completely gone now.

The native notification window is opened here now:
https://searchfox.org/comm-central/rev/89dbe9128a35940096d61f7b6914ba8c979d1115/mailnews/base/src/MailNotificationManager.sys.mjs#397-403

`openWindow()` is defined here:
https://searchfox.org/mozilla-central/rev/f0b3dafb55f1e7904847f5dc889f131040789ba6/toolkit/components/windowwatcher/nsIWindowWatcher.idl#67

We don't have a dual-monitor setup for Linux, so is you want to try a fix, do this:
In your BB installation, rename omni.ja to omni.zip. Unzip it.
Find the file MailNotificationManager.sys.mjs (it's .jsm instead of .sys.mjs if you're on 115), find that code and change the first argument `null` to this: `Services.wm.getMostRecentWindow("mail:3pane")`. So you're telling the system to open the alert window as child of the latest main BB window. If that helps, we can change the code in BB. However, https://bugzilla.mozilla.org/show_bug.cgi?id=637830#c14 suggests, that it may not help.

**Comment by konstanzzz** [comment]
Thanks for the response. It seems I do not have an `omni.ja` file. I have a Flatpak installation if it makes a difference.

**Comment by Betterbird** [comment]
Well, then you will need to invest some work and install the tar.bz2. That said, surely the FlatPak installs the same files somewhere, so the omni.ja will be somewhere.

Additional information: The window position is also determined here:
https://searchfox.org/comm-central/rev/89dbe9128a35940096d61f7b6914ba8c979d1115/mailnews/base/content/newmailalert.js#68-74

There are not only the object properties of `screen`, but also others, like `screenX`, `screenY`, `screenTop` and `screenLeft` which can be used in the calculation.

**Comment by konstanzzz** [comment]
> change the first argument `null` to this: `Services.wm.getMostRecentWindow("mail:3pane")`.

Unfortunately like what the others suspected, this didn't work.

> Additional information: The window position is also determined here:
> https://searchfox.org/comm-central/rev/89dbe9128a35940096d61f7b6914ba8c979d1115/mailnews/base/content/newmailalert.js#68-74

Thanks - will take a look and see if I can come up with a workaround.

**Comment by Betterbird** [comment]
The issue is also that there is no right solution: Some people will want the notification rising from the system tray on the primary display, some may want it to rise from the window where the application is on.

I've played around with this a bit, pasting this into the Error Console (Ctrl+J):
```
Services.ww.openWindow(
      Services.wm.getMostRecentWindow("mail:3pane"),
      "chrome://messenger/content/newmailalert.xhtml",
      "_blank",
      "chrome,dialog,titlebar=no,alert=yes",
      null
    );
```
That's without moving the window to the bottom right in the JS code in newmailalert.js.

Regardless of where the my main BB window is placed, the alert window always shows up on the the primary monitor.

I've played around with `console.log(screenLeft)` in the error console. This appears to measure how far the left edge of the main window is to the left edge of the primary display. If I move the main window to a monitor to the left of the primary monitor, so 
[secondary screen][primary screen], I get screenLeft = -1926. If the secondary screen is to the right of the primary screen, then screenLeft is larger than the width of the primary screen.

Maybe something like this can be used to detect that the main windows is not on the primary screen and in this case execute different code in newmailalert.js to move the alert window to a different position which windows will associate with another screen.

Since you are (on the way to becoming) a JavaScript programmer, maybe you want to tweak the code I indicated. If you come up with a solution, we're happy to integrate it.

Maybe so start, at the code indicated, insert `console.log(x,y)` to see where the alert window is moved. Then add `x+= 100` to see where it moves to, or `x -= 100`. As long as your screens are of equal height resolution, that should move the alert window horizontally. I guess `x -= <width-of-primary-screen>` will move it to the bottom corner of a secondary screen on the left, where as `x += <width-of-secondary-screen>` will move it to the bottom corner of a secondary screen on the right.

Lots of fun.

**Comment by konstanzzz** [comment]
> The issue is also that there is no right solution: Some people will want the notification rising from the system tray on the primary display, some may want it to rise from the window where the application is on.

Hmm, in that case would it be easier to implement a feature that opens BB when the system (non-native) notification is clicked? At least this way the notif position can be configured through the OS.

**Comment by Betterbird** [comment]
Starting the application from the system notification after it has been 
closed leaving its notifications behind, is a non-starter. Firstly it 
would mean digging around in Linux system internals; with the same 
situation on Windows, the TB devs decided to remove all system 
notifications when TB closes. That was implemented for 128 and if I'm not 
mistaken also applies to Linux. Apart from being too hard to implement on 
Windows and likely Linux (as mentioned), they argued with privacy 
concerns, which is a somewhat valid argument (of course someone having 
access to your machine can do worse damage then looking at stale 
notifications).

Besides, why would you want this function when the native notification 
disappears after a few seconds and is definitely closed with the main 
application.

Or is there some misunderstanding? Clicking on the system notification 
while TB or BB is running brings the (minimised) window forward and 
selects the corresponding message. Does that not work for you?

Re. the native notification, we've given some suggestions for 
experimentation, so please follow those. Otherwise, we can look into it 
in due course after securing some funding.

We imagine that the solution will look like this: Introduce a pref to opt 
for opening the alert on the application screen, not the primary screen. 
In that case, get the screen geometry of the application screen and the 
primary screen and move the window which opened on the primary screen to 
the bottom right of the application screen. Not trivial, would need some 
time to explore.

**Comment by konstanzzz** [comment]
> Clicking on the system notification while TB or BB is running brings the (minimised) window forward and selects the corresponding message. Does that not work for you?

This is what I would like to happen, but this does not work currently, at least not on Debian 12 + KDE.

> Re. the native notification, we've given some suggestions for experimentation, so please follow those.

Yes, I've been playing around with it, thanks. Although of course a cleaner solution would be preferred over something that works only for a very specific setup.

> Otherwise, we can look into it in due course after securing some funding.

This is well understood. I also realize there are other open issues that are most likely higher prio than this one so I appreciate your time helping with this.

Thanks.

**Comment by Betterbird** [comment]
> > Clicking on the system notification while TB or BB is running brings the (minimised) window forward and selects the corresponding message. Does that not work for you?
>
> This is what I would like to happen, but this does not work currently, at least not on Debian 12 + KDE.

What exactly doesn't work? I tried with Mint 20 + KDE and Mint 20 + Xfce. for both, clicking on the system notification brings the (minimise) window to the foreground and shows the new messages, albeit, there is some issue. At times I see this in the error console:
```
18:31:27.027 Finding first new message for folder imap:// ... /INBOX failed with Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIMsgFolder.firstNewMessage] 2 mailCommon.js:1085:19
```

> > Re. the native notification, we've given some suggestions for experimentation, so please follow those.
> 
> Yes, I've been playing around with it, thanks. Although of course a cleaner solution would be preferred over something that works only for a very specific setup.

Sure, see the envisaged solution two comments up. I you wanted you to play around with `window.screen`, `window.screenLeft` and `Services.wm.getMostRecentWindow("mail:3pane").screen and Services.wm.getMostRecentWindow("mail:3pane").screenLeft` to see whether we can come up with some code that can work out where the primary screen is relative to the application screen.

**Comment by Betterbird** [comment]
OK, we worked it out: Replace
https://searchfox.org/comm-central/rev/89dbe9128a35940096d61f7b6914ba8c979d1115/mailnews/base/content/newmailalert.js#68-74
with
```
  // Show in bottom right, offset by 10px.
  // We wait one cycle until the window has resized.
  const appWindow = Services.wm.getMostRecentWindow("mail:3pane");
    
  setTimeout(() => {
    let screenToUse = screen;
    if (appWindow.screenLeft < 0) {
      // Application screen to the left of the primary screen.
      screenToUse = appWindow.screen;
    } else if (appWindow.screenLeft > screen.width) {
      // Application screen to the right of the primary screen.
      screenToUse = appWindow.screen;
    }
    const x = screenToUse.availLeft + screenToUse.availWidth - window.outerWidth - 10;
    const y = screenToUse.availTop + screenToUse.availHeight - window.outerHeight - 10;
    window.moveTo(x, y);
  });
```
This should always show the alert on the application screen, regardless of whether it's to the left or the right of the main screen.

We'll wrap it into a pref and ship it in the next version.

**Comment by Betterbird** [comment]
Try https://www.betterbird.eu/downloads/LinuxArchive/betterbird-115.16.0-bb33-latest-build.en-US.linux-x86_64.tar.bz2 and set pref mail.notification.show_on_app_screen. We suggest that you delete the installation where you unpacked omni.ja completely.

**Comment by konstanzzz** [comment]
> Try https://www.betterbird.eu/downloads/LinuxArchive/betterbird-115.16.0-bb33-latest-build.en-US.linux-x86_64.tar.bz2 and set pref mail.notification.show_on_app_screen. We suggest that you delete the installation where you unpacked omni.ja completely.

Thanks. This worked initially but somehow it reverted back to popping up on my second monitor after minimizing to tray and doing something else on my other monitor. I never moved BB to the second monitor by the way, so I'm not sure what triggered it. The behavior is quite inconsistent and I cannot reliably reproduce it.

> What exactly doesn't work? I tried with Mint 20 + KDE and Mint 20 + Xfce. for both, clicking on the system notification brings the (minimise) window to the foreground and shows the new messages

OK, it seems the problem only exists in the Flatpak package. I switched to the .tar.bz2 and it works. I'll stick to this solution for now. Appreciate your help!

**Comment by konstanzzz** [comment]
Sure, basically BB was opened on the primary screen, never moved to non-primary. So this means the primary screen has been the application screen the entire time. If it matters BB was minimized to tray and moved between virtual desktops but always on the primary screen. Thanks.

**Comment by Betterbird** [comment]
So if BB is always on the primary screen than primary screen and application screen are the same? So why is there a problem in the first place?

On Windows, with the "latest version" I published, everything works fine, regardless of whether the application screen is to the left or the right of the primary screen. Only observed oddity: If the the application screen is to the right and BB is minimised, then the alert shows up on the primary screen. It doesn't happen when the application screen is to the left.

**Comment by konstanzzz** [comment]
So my setup is [secondary][primary], and somehow the popup eventually ends up on the left (secondary) screen. The latest version worked fine initially but after doing a few things on the secondary screen, notifications started appearing there and never moved back to primary. It stays this way even with the primary having the cursor and also the currently focused window.

**Comment by Betterbird** [comment]
> Only observed oddity: If the the application screen is to the right and BB is minimised, then the alert shows up on the primary screen. It doesn't happen when the application screen is to the left.

We looked at this a bit more, there are two cases:

Application screen to the left: [app screen][primary screen].
When the app main window is minimised or not, `Services.wm.getMostRecentWindow("mail:3pane").screen` reports the properties of the left app screen and the alerts always open there.

Application screen to the right: [primary screen][app screen].
When the app main window **is not** minimised, `Services.wm.getMostRecentWindow("mail:3pane").screen` reports the properties of the right app screen and the alerts open there.
When the app main window **is** minimised, `Services.wm.getMostRecentWindow("mail:3pane").screen` reports the properties of the primary screen and the alerts open there instead of on the app screen as desired.

Getting those window/screen properties is using the underlying Mozilla platform which appears to have a bug. Of course it's questionable which screen a minimised app is on, since it's on no screen. We could work around the issue by tracking the screen of the main window and using the screen it was on before getting minimised. That solution won't work on Wayland since there, we don't receive the notification when the main window is minimised, see Issue #279.

We might re-open the issue to address this quirk.

**Comment by Betterbird** [comment]
Further improvements in to ship in the next release:
https://github.com/Betterbird/thunderbird-patches/commit/5e85f37dc749bf64ee0a79201a3687b2078b2230
https://github.com/Betterbird/thunderbird-patches/commit/39b1a4206c4c92936156039023fbf00eda2c64eb
