### ISSUE TITLE
Mark as Read missing from Unread Folder

### ISSUE THREAD

**Issue by gotspatel** [Betterbird/thunderbird-patches#351]
After update to betterbird-115.16.0-bb33 from betterbird-115.15.0-bb32 [corrected to 115.15.0-bb32]

Mark as Read option is missing from the Unread Search Folder. Please bring it back.

Thanks

**Comment by Betterbird** [comment]
Correct, in 115.16.0-bb33 we included the fix to https://bugzilla.mozilla.org/show_bug.cgi?id=1909617. The function wasn't working, when you marked the search folder as read, the underlying base folder was marked read. That's why the TB folks decided to remove it from the menu since they saw no way to only mark the messages contained in the search folder as read in the base folder.

Have you not experienced that issue or was it even a desired "feature"?

**Comment by gotspatel** [comment]
Thank you for clarification, didn't notice it until NOW :-)

But I would love it as a feature update for sure.
