### ISSUE TITLE
Crashing when deleting a mail

### ISSUE THREAD

**Issue by Mieekaserra** [Betterbird/thunderbird-patches#353]
Just installed betterbird-128.3.1esr-bb12.en-US.win64.installer

When deleting a mail from the mail box, betterbird closes without a error message. Windows event viewer shows the following

Faulting application name: betterbird.exe, version: 128.3.1.0, time stamp: 0x6707cf77
Faulting module name: xul.dll, version: 128.3.1.181, time stamp: 0x6707d184
Exception code: 0xc0000005
Fault offset: 0x00000000002bb208
Faulting process id: 0x0x1E04
Faulting application start time: 0x0x1DB1E1075A38B20
Faulting application path: C:\Program Files\Betterbird\betterbird.exe
Faulting module path: C:\Program Files\Betterbird\xul.dll
Report Id: 75073c89-3e02-47ef-b50c-9ed928230ffa
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Betterbird** [comment]
You're deleting from a local or IMAP folder? The folder is stored as mbox or maildir? Works here for local + IMAP and mbox format, we'll test maildir shortly. Could be related to https://github.com/Betterbird/thunderbird-patches/commit/3388b8a8358e62843ec33c9b028c34fdfeef4b72.

**Comment by Mieekaserra** [comment]
Local folders, Pop3 mail.

**Comment by Betterbird** [comment]
mbox or maildir?

**Comment by Mieekaserra** [comment]
Mbox

**Comment by Betterbird** [comment]
Hmm, well, I'm doing this:
Have a POP account with mbox storage, a few unread messages. Click on an unread one, it displays in the message pane, then turns unread. I delete the message, I read another one, shift-delete it. No crash. During development we had a crash in that situation for maildir stored folders, but that got fixed and was never shipped broken. Does TB 128.3.1 also crash? Does is crash on all mailboxes or just a particular one? We don't know how widely used 128 is so far, but it is crashed for everyone always, we would have heard about it earlier.

**Comment by Mieekaserra** [comment]
No, Thunderbird 128.3.1 is fine,  as is 128.3.0 of betterbird.

All i did this morning was update my betterbird and it started crashing on delete.

**Comment by Betterbird** [comment]
OK, the difference between TB 128.3.1/BB 128.3.0 and BB 128.3.1 is that in BB 128.3.1 we restored the mbox envelop date using the patches from https://bugzilla.mozilla.org/show_bug.cgi?id=1911916#c31 and an additional one
https://github.com/Betterbird/thunderbird-patches/blob/main/128/bugs/1911916-extra-transfer-envaddr-envdate-in-copy.patch
to preserve the envelop date also during moving/copying a message. Since deleting moves the message to the trash, that could be the culprit, although we can't reproduce the crash here.

How about trying TB 132 beta (https://download.mozilla.org/?product=thunderbird-beta-latest-SSL&os=win64&lang=en-US), which contains the patches from bug 1911916 but obviously not our additional patch. If TB 132 crashes, we know it comes from those changes, if it doesn't crash, we can build a special version without our additional patch to see whether this is the cause. If TB 132 crashes, please supply the crash ID which can be found in "Help > Troubleshooting Information" after having submitted the crash report to Mozilla.

**Comment by Betterbird** [comment]
Here's a build with the patches from the TB folks, but without our additional patch:
www.betterbird.eu/downloads2/betterbird-128.3.1esr-bb12-special-build-no-env-date-on-copy.en-US.win64.installer.exe

If that crashes, then TB 132 beta would crash as well and you can submit a crash report, if it does not crash, than our additional patch is causing a problem.

**Comment by Betterbird** [comment]
Thanks for testing, that indicates that it's our fault then :cry:

**Comment by Mieekaserra** [comment]
This doesnt crash either, I only have one mailbox (everything goes to local folder).

Other than what is in event viewer - i don't see any crash reports (both crashes and minidumps folders are empty in my profile directory).

**Comment by Mieekaserra** [comment]
This is the information for the most recent crash (i redownloaded from website incase installer was corrupt) 

Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: betterbird.exe
P2: 128.3.1.0
P3: 6707cf77
P4: xul.dll
P5: 128.3.1.181
P6: 6707d184
P7: c0000005
P8: 00000000002bb208
P9: 
P10: 

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4270a0c9-e8ca-4226-bf45-8d91e794d66b
Report Status: 100
Hashed bucket:

**Comment by Betterbird** [comment]
If "take 2" didn't crash, that hopefully this version "take3" here won't crash either:
www.betterbird.eu/downloads2/betterbird-128.3.1esr-bb12-special-build-with-env-date-on-copy-take3.en-US.win64.installer.exe

This restores the "env date" function, but adds a special check to avoid the crash. We tried everything, but it doesn't crash here. It's likely related to your (large?) (old?) mailbox which may need to be repaired. But don't do anything before trying the latest version above.

BTW, "Exception code: 0xc0000005" is likely caused by dereferencing a null pointer and that exactly is checked now.

**Comment by Mieekaserra** [comment]
Take 3 crashes
[Report.zip](https://github.com/user-attachments/files/17365603/Report.zip)
.

Repaired the mailbox - still crashes.

EventData 

  AppName betterbird.exe 
  AppVersion 128.3.1.0 
  AppTimeStamp 670d2924 
  ModuleName xul.dll 
  ModuleVersion 128.3.1.181 
  ModuleTimeStamp 670d292a 
  ExceptionCode c0000005 
  FaultingOffset 00000000002bb208 
  ProcessId 0x2550 
  ProcessCreationTime 0x1db1e4773bc9d40 
  AppPath C:\Program Files\Betterbird\betterbird.exe 
  ModulePath C:\Program Files\Betterbird\xul.dll

**Comment by Betterbird** [comment]
We can't reproduce the crash. What makes your case special? Are you deleting the first or last message in the mailbox, or in the middle? You're deleting one message or multiple? Delete move to the trash or are you using shift+delete?

**Comment by Betterbird** [comment]
Maybe you can create another mailbox, copy some message into it (shift+drag) with a version that doesn't crash and then try deleting from the small mailbox. If that still crashes, provide us with the small mailbox (raw message file and .msf file).

**Comment by Betterbird** [comment]
We found the crash: It crashes when this option is selected "Allow antivirus clients to quarantine individual incoming messages". It's quite clear what happens there. We'll fix it.

**Comment by Mieekaserra** [comment]
I do have that option on - i'm glad you found it!

**Comment by Betterbird** [comment]
Please download the installer again, you will get "build 2" now:
https://www.betterbird.eu/downloads/get.php?os=win&lang=en-US&version=future

That fixes the issue.

**Comment by Betterbird** [comment]
Thanks for reporting the issue, for testing, for you patience and the final confirmation. Much appreciated!!
