### ISSUE TITLE
The cache is not used for a virtual folder (saved search) if one of the inboxes is not contributing. 

### ISSUE THREAD

**Issue by viking2** [Betterbird/thunderbird-patches#370]
I have a Saved Search using 14 inboxes and one of the rules is "Age in Days is less than 3"
If one of the 14 inboxes had no messages in the last 3 days, that inbox is not contributing and the cache is therefore not used; the folder is always searched when selecting it.

**Comment by Betterbird** [comment]
Yes, this was widely discussed before. There is no API to remove tables from the Mork database, hence the cache table can't be removed, all we can do is set it to zero entries. There for "no cache" and "empty" cache can't be distinguished.

We've considered storing a "cache invalid" flag somewhere else, but that's a whole lot more effort.

Implementation note: That could be done via a folder flag or nsIMsgFolder.setStringProperty() on the virtual folder itself. However, since the cache is stored on the contributing folder(s), this can lead to inconsistencies if the database of the contributing folder (the .msf file) is deleted or repaired. One would have to notify all search folders based on the contributing folder to mark their cache invalid. Potentially that can be mitigated by the fact that database deletion/repair will remove the cache table altogether, from which fact the invalidity of the cache can be derived.

That pity is that virtual folder caching occupies a large part of our development capacity, but there's only one user with a large amount of data using the functionality.

**Comment by Betterbird** [comment]
Implemented in https://github.com/Betterbird/thunderbird-patches/commit/89cb52e9b95638e704381ef657632fced43d3c04.

Try:
https://www.betterbird.eu/downloads/WindowsInstaller/betterbird-115.18.0-bb36-preview.en-US.win64.installer.exe
This is the release preview, so you need to set pref `mailnews.virtual_folders.verbose` to get the logging.

Note that since we introduced a "cache valid" flag, all existing searches will be redone since the folder doesn't have the flag yet.
