### ISSUE TITLE
Update to version 128.5.0esr freezes "filter messages"

### ISSUE THREAD

**Issue by jmrohwer** [Betterbird/thunderbird-patches#379]
I've been using betterbird for the better part of a year on Manjaro Linux with the AUR package. Since the update to 128.5.0esr, trying to filter messages in the message list (via `Ctrl`-`Shift`-`K`) freezes Betterbird indefinitely. The message list stays blank and no filtered messages appear even after a long time (>1 min). This happens even when the folder has very few (~5) messages.

At first I thought it was related to the following bug in TB: https://bugzilla.mozilla.org/show_bug.cgi?id=1908761
However, that bug has been fixed and there are important differences in that the filtered messages never appear on BB even after a very long wait.

I've installed and run TB (128.4.4 - the current version on Arch/Manjaro) as well as version 128.5.0 (downloaded directly from the TB website), and indeed message filtering works flawlessly in both (using the same profile as for BB).

This is an absolute deal breaker for me as I use message filtering all the time, and BB has become unusable as a result. In the mean time I've reverted to using TB.

**Comment by Betterbird** [comment]
This is absolutely unbelievable. We use so-called Quick Filter every two minutes (without exaggeration). Sure, it takes a little longer (body) searching a folder with 200.000 messages, but "smaller" folders are instant, and for 5 messages it takes a split second.

We're easily irritated by language like "deal breaker". Which deal do we have exactly? Are you paying for the software? Have you made a donation, we have none in your name on file, but our records could be wrong.

Are you running TB and BB on the same profile? Have you read the support page?

If you choose to contact us, please provide the required information as follows:

    Operating system and version of operating system. For Linux, distribution and desktop environment as well as graphic interface (X11/Wayland).
    State your anti-virus program, if any.
    State your hardware: RAM, disk size, type of fixed disk (SSD, etc.).
    Version of Betterbird. For Linux, how it was installed: FlatPak, Arch Linux AUR, installed from .tar.bz2, maybe via our [installation script](https://github.com/Betterbird/thunderbird-patches/blob/main/install-on-linux/install-betterbird.sh).
    State how many accounts you have and of which type and state with which account type the issue happens: IMAP, POP, Feeds, News, Chat. For IMAP, state whether the folder producing the problem is synchronised for offline use or not. For all account types: How many messages? How big is the folder in KB, MB or GB. This is especially important for performance issues.
    State whether you have configured any online services, like CalDAV calendars or CardDAV address books, potentially via NextCloud.
    **Check whether the problem reproduces with all add-ons switched off: Help > Troubleshoot Mode.** Reset the startup cache: Help > Troubleshooting Information, Clear startup cache.
    Have you manipulated any preferences, perhaps via user.js? Are you using userChrome.css or userContent.css?
    For performance issues, submit a (startup) performance profile, see [Mozilla's documentation](https://profiler.firefox.com/docs/#/./guide-startup-shutdown?id=profiling-firefox-startup-amp-shutdown) for details. Note that after capturing the profile via Tools > Developer Tools > Developer Toolbox, Performance, you need to click Upload local profile, but instead of uploading to Mozilla, click Download. Then submit the data to our support, for big files, use a file transfer service.
    Does the issue happen in Thunderbird when run on the same profile? Comparisons with Thunderbird running on a different profile are not meaningful. This question of course doesn't apply to Betterbird-only features.
    For "can't send" or "can't receive" problems, disable your anti-virus program, either for the Betterbird executable, or its installation directory or both. Generally it's not necessary and not recommended to exclude your profile from the anti-virus protection, unless you're experiencing sluggishness which may be related to anti-virus scan delays.
    Note that profiles on network drives are only partly supported, profiles in Dropbox folders don't work at all.
    Be smart! We leave it to your own judgement which information is relevant for your particular case.

Let us guess. You're using **Cardbook** and haven't read this section in the FAQ (https://www.betterbird.eu/faq/):

UPDATE: The popular CardBook add-on has only limited compatibility with Betterbird since it modifies the underlying application code at runtime (so-called [monkey patching](https://en.wikipedia.org/wiki/Monkey_patch)). The modifications are designed for Thunderbird and make Betterbird malfunction in the area of the Quick Filter Bar. Malfunction is more severe in Betterbird 128 than in Betterbird 115.

As a temporary fix we are providing a version of CardBook with the offending code removed, [download here](https://www.betterbird.eu/downloads/Addons-fixed-for-BB/cardbook-94.5-fixed-for-BB@vigneau.philippe.xpi) (use Save Link As).

Anyway, whatever the case will be, we can't fix it on the information you provided. If it's not Cardbook, you need try this on an new profile and submit a performance profile. We can re-open the ticked of required.

Also see:
https://www.reddit.com/r/Betterbird/comments/1h48j7u/12850esrbb18_cardbook_break_quick_filters/

**Comment by Betterbird** [comment]
We've updated the replacement:
https://www.betterbird.eu/downloads/Addons-fixed-for-BB/cardbook-97.7-fixed-for-BB@vigneau.philippe.xpi

From the next version 128.5.2 incompatible add-ons will be blocked.
