### ISSUE TITLE
With betterbird 128.5.2 latest build 19 is impossibile to open pdf attached from scanner program 

### ISSUE THREAD

**Issue by loris783** [Betterbird/thunderbird-patches#383]
I have only white page when i double click on pdf attached.
Why?

Hyperweb

**Comment by Betterbird** [comment]
Sorry, but you haven't really supplied any relevant details.

We're not in the business of second-guessing what you might have done. Perhaps, you're using Windows, perhaps, you have a scanning suite that can (supposedly) send a scanned document via e-mail, perhaps that scanning suite communicates with TB or BB via MAPI, perhaps your report is misleading since apparently, maybe, a compose window does get opened, only that there is no PDF attached, or the one that's attached is faulty, or whatever else you didn't mention.

Please get into the habit to file actionable bug reports and not use GitHub issues for support requests. Also, read https://www.betterbird.eu/support/index.html#support-info to get a vague idea of what sort of information may be required.
