### ISSUE TITLE
Default button doesn't look correct if dark system theme is used on Linux

### ISSUE THREAD

**Issue by PoisonFrog** [Betterbird/thunderbird-patches#50]
I noticed some buttons in Betterbird do not follow the applied theme while in Thunderbird they do.

In Betterbird they look like this:

![Betterbird1](https://i.imgur.com/mlwFnbj.png)

![Betterbird2](https://i.imgur.com/htttktQ.png)

In Thunderbird the buttons are using proper theming and looks like this:

![Thunderbird1](https://i.imgur.com/lHXhu3s.png)
![Thunderbird2](https://i.imgur.com/s5RxNTs.png)

I saw these button issues at the new filter window and the toolbar customization window.

**Comment by Betterbird** [comment]
Right, TB has those horrible blue default buttons which we've changed a bit. Looks OK here:
![image](https://user-images.githubusercontent.com/86832723/164114710-a9bd0233-cbc1-4b9a-b0f5-e656760749f0.png)

and here:
![image](https://user-images.githubusercontent.com/86832723/164114899-fcc2d6d6-e8ee-451c-8b4a-6ecf388b2389.png)

and here:
![image](https://user-images.githubusercontent.com/86832723/164114964-eaa32a42-e37c-4ce1-9910-e1545efa779a.png)

That's all on Windows. We've just checked the latest version of BB on Mint and it looks like on Windows, light grey buttons, not blue like in TB but also not white like in your screenshots.

Sorry, can't reproduce, must be something on your Linux installation. I've seen the funniest colours on Linux, like white on white, etc.

**Comment by Betterbird** [comment]
@posi81: Buttons looking OK for you, light grey in the dark theme?

**Comment by Betterbird** [comment]
Here a Linux screenshot of the customise panel you have in your screenshot:
![image](https://user-images.githubusercontent.com/86832723/164117273-df9c2bbd-62b2-4519-aa3c-0246a43adbe3.png)

**Comment by Betterbird** [comment]
Works on Mac, too:
![image](https://user-images.githubusercontent.com/86832723/164175620-60b42e28-d9ae-487a-8f9d-b58aa80ae444.png)

@PoisonFrog: Are you using modifications in userChrome.css?

**Comment by PoisonFrog** [comment]
> ![image](https://user-images.githubusercontent.com/86832723/164175620-60b42e28-d9ae-487a-8f9d-b58aa80ae444.png)

No, I'm not. The theme is just inheriting from my GTK theme. It's not a big issue or anything like that. I just find it weird that I only have this issue with Betterbird while in Thunderbird it looks normal.

**Comment by Betterbird** [comment]
As I said, BB has made CSS changes related to the look of the button, they are blue in TB and light grey in BB in the dark theme and and lighter then the other buttons in the light/standard themes. The code here
https://github.com/Betterbird/thunderbird-patches/blob/7071c49406bfb97a191df66cb3889ab92b63be88/91/features/05-feature-default-buttons.patch#L58
pulls the original colour up to white. Maybe your GTK theme has light buttons, so they go even lighter now. How do the buttons look like in TB 78 before the buttons went blue in https://bugzilla.mozilla.org/show_bug.cgi?id=1730153?

Maybe we'd have to fix the button bg colour to protect against people like you 😁 - Can you turn down the general button bg colour in your GTK theme and see whether it makes a difference?

**Comment by PoisonFrog** [comment]
I use a fork of the _Matcha-dark-azul_ GTK theme. The buttons in this theme do not have light color. Button color outside Thunderbird is #262A32 most of the time. Firefox and Thunderbird don't follow all GTK coloring, but they inherit some of it if you are using system theme.

**Comment by PoisonFrog** [comment]
This issue happens with all Dark GTK themes I tried.

This is how the Dracula theme (a very popular theme in Linux) looks in Thunderbird:

![Thunderbird](https://i.imgur.com/v8A2YVL.png)

And this is how it looks in Betterbird:

![Betterbird](https://i.imgur.com/gXuNGF6.png)

It is the same for other themes. Thunderbird inherits the main accent color and uses it for these buttons while Betterbird uses a white color.

**Comment by Betterbird** [comment]
Right. Maybe you can open the Inspector (Tools > Developer Tools > Developer Toolbox), select the window that shows the button, and then inspect the button, like so:
![image](https://user-images.githubusercontent.com/86832723/164281911-3a1635d9-40c5-4c73-8469-5c564bb233c1.png)

If you switch off the background colour rule, you'll see what --button-bg is meant to be, like so:
![image](https://user-images.githubusercontent.com/86832723/164282112-1e7088f9-8d2c-48ac-9359-57b7db91fdab.png)

You can hover it to get the value:
![image](https://user-images.githubusercontent.com/86832723/164282271-9c1afb01-2451-4e40-9beb-c211fdd24ec6.png)

I get 43, 42, 51, which is rather dark, and with the rule, enabled, it goes a bit lighter. I bet you have a rather light --button-bg colour.

TB doesn't show the issue since it sets the button to blue, then end.

**Comment by Betterbird** [comment]
OK, I installed Dracula myself now:
https://snapcraft.io/install/dracula-gtk-theme/mint
```
sudo rm /etc/apt/preferences.d/nosnap.pref
sudo apt update
sudo apt install snapd
sudo snap install dracula-gtk-theme
```
And now? How to enable it?

**Comment by Posi81** [comment]
Hello together....
If i use inside Betterbird the own DarkTheme then it looks like this...
![image](https://user-images.githubusercontent.com/59346176/164294229-a4446042-bc33-499b-be1b-838355b953f2.png)

if i use activate in Betterbird to use the Systemtheme for me (Lyan-Dark solid), then it looks like this (same problem)
![image](https://user-images.githubusercontent.com/59346176/164294554-d7148b3f-a595-49f5-89a4-ceac6e0b771f.png)

**Comment by Posi81** [comment]
`gsettings set org.gnome.desktop.interface gtk-theme "dracula-gtk-theme"`

**Comment by Posi81** [comment]
`xfconf-query -c xsettings -p /Net/ThemeName -s "dracula-gtk-theme"`

**Comment by Posi81** [comment]
gsettings set org.gnome.desktop.interface gtk-theme "Dracula"

**Comment by PoisonFrog** [comment]
> Nothing happened. This is on Mint 20 with Xfce.

On Xfce you can just open the Appearance app and switch the style to Dracula.

**Comment by Betterbird** [comment]
OK, we figured out what the issue is. When you use a system theme, TB/BB's "dark theme" rules aren't applied, instead the "normal" rules are applied which are used for light themes on all other platforms. And in a light them, the button is made quite bright, as we can see.

I don't know that Dracula ever got installed, and some of the "dark" themes aren't really dark, but Mint-Y-Dark-Purple is dark. Using it, I see the effect now (finally). The issue is due to what I wrote in the previous paragraph, the system theme, a concept only supported on Linux, not treated as dark but "normal".

For the time being, I suggest to switch to BB's own dark theme. We'll address the bug in the next release in early June.

**Comment by Betterbird** [comment]
Done.

**Comment by Betterbird** [comment]
@PoisonFrog: Please try: https://www.betterbird.eu/downloads/LinuxArchive/betterbird-91.8.1-bb30-latest-build.en-US.linux-x86_64.tar.bz2
This also contains the new logical expression feature (issue #35). Please take a good read of https://github.com/Betterbird/thunderbird-patches/issues/35#issuecomment-1104040730 re. incompatibilities with TB stored rules.
