### ISSUE TITLE
BB uses > 25 % CPU since 8 hours, no change after restart

### ISSUE THREAD

**Issue by CoSoCo** [Betterbird/thunderbird-patches#61]
There is a new performance problem since TB 91.10.0 which also appears with Betterbird 91.10.0-bb33
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1772673

I'm running TB 91 on my production system Ubuntu 20.04. Downgrading to a lower Version is not possible, as my now updated TB profile won't work with it.
With this bug, using my production system is a real pain.

Please engage in a solution.

**Comment by Betterbird** [comment]
So you expect us to fix the 14.000+ bugs that the 20 people TB team doesn't want to touch?

This is likely impossible to fix since the issue will be to some configuration on your Linux box. If it were a common problem on Linux, more people would have complained.

We suggest to use profiling and post your results to the TB ticked you opened.

https://profiler.firefox.com/docs/#/

**Comment by CoSoCo** [comment]
> So you expect us to fix the 14.000+ bugs that the 20 people TB team doesn't want to touch?

Not really, but as you have advertised, that you fix bugs, that the TB-team doesn't care about, I thought, it might be interesting for you, to have a look at this issue.

Ok, I don't know, if many people have encountered this problem. Unfortunately I'm stuck now how to find, what could be wrong in my configuration.

> We suggest to use profiling and post your results to the TB ticked you opened.

As you can see [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1772673), I already reported the profiling result.

**Comment by Betterbird** [comment]
We've commented on the bug, that's as much as we can do. The issues seems to be your setup plus some issue in the Mozilla platform code.
