### ISSUE TITLE
Betterbird Portable is not portable

### ISSUE THREAD

**Issue by SlaveOfCats** [Betterbird/thunderbird-patches#64]
I have Betterbird Portable "installed" in a folder on my desktop (Win10). If I try to move or rename the folder and then launch Betterbird, my add-ons no longer work. 

Betterbird 91.11.0-bb34 (64-bit).

**Comment by Betterbird** [comment]
That's a known issue that was fixed in commit https://github.com/Betterbird/thunderbird-patches/commit/87ae2b0c3605e6a17ad4a017dbad80ef41e9e2b4.
Replace the launcher with the latest version from here https://github.com/Betterbird/thunderbird-patches/blob/main/BetterbirdLauncher/BetterbirdLauncher.exe and in the Config Editor set extensions.startupScanScopes to 5.

Happy moving or renaming.

**Comment by SlaveOfCats** [comment]
Thanks!

I understand that not many people will find this issue. I found it because I was doing several test installs so that I could compare with ThunderbirdPortable. When I was done, I wanted to move my final Betterbird folder to a more permanent location, only to discover that it didn't work afterward. All is well now, though.

**Comment by Betterbird** [comment]
We've added a lot of code to the launcher so it will cope with moving the folder. No tricks needed for add-ons, the "just work"(TM). It will ship with BB 115.3.0 this week.
