### ISSUE TITLE
Betterbird Portable doesn't work with mailto from Firefox

### ISSUE THREAD

**Issue by SlaveOfCats** [Betterbird/thunderbird-patches#66]
WIndows 10, Betterbird Portable 91.12.0-bb35

I set Betterbird Portable as the default mail program. In Firefox settings, there are 2 Betterbird options for mailto: Betterbird and BetterbirdLauncher. Neither works when a mailto link is clicked.

If Betterbird is configured, then a compose window is opened with no recipient, plus another window is opened offering to configure a new newsfeed account. If I exit that, then both windows close.

If BetterbirdLauncher is configured, then after a few seconds, an error message is displayed saying that Betterbird is running but not responding.

**Comment by Betterbird** [comment]
This goes far beyond what a simple portable can achieve. In our opinion, default program and portable are mutually exclusive. You can easily have the portable on a USB stick and remove it. So what happens to your default program then?

What you're asking for is not supported.

**Comment by SlaveOfCats** [comment]
Was wondering because Thunderbird Portable from PortableApps supports it (with registry tweaks). 

Sorry to raise a ticket about it. The reason for doing that is that I actually have a different question about BB, and the only way to ask a question is this or the encrypted mailto link on the Betterbird.eu site.

**Comment by Betterbird** [comment]
Look, neither TB nor BB are designed for portable use. The profile contains files which record native absolute path names, as soon as you move the setup, things break. The TB team have been wise not to offer a portable version and they are not connected to all the portable stuff that floats around, https://portableapps.com/ being the most sophisticated (but there are others). However, they don't mitigate the native absolute path and their portable also creates these files:
C:\Users\<User>\AppData\Local\Thunderbird and C:\users\<User>\AppData\Roaming\Thunderbird

We won't invest any more effort into making something portable which by design is **not** portable. What works works, what doesn't work won't be fixed. If you're talking about registry tricks, then I don't understand why you don't simply install the program as it was designed. The installer makes the necessary registry adjustments.

As for support: The support e-mail address is published, if the mailto link doesn't work for you, just mail to support at ...

**Comment by SlaveOfCats** [comment]
I wasn't trying to argue with you, just trying to get answers. I won't be wasting any more of your time after this!
