### ISSUE TITLE
Signed Windows Installers

### ISSUE THREAD

**Issue by ovari** [Betterbird/thunderbird-patches#67]
It is understood that the Windows version is not signed. If this is not the case, perhaps this issue should be closed.

Have you heard of VMware [InstallBuilder](https://installbuilder.com/) `A powerful and easy to use cross platform installer creation tool`?

InstallBuilder provides free licenses to their program. For details, please visit https://installbuilder.com/open-source-licenses.html.

Perhaps this program can enable Windows Installers to be signed?

There may be benefits for GNU/Linux and macOS editions as the software is cross platform.

What do you think?

Thank you

**Comment by Betterbird** [comment]
The Windows builds **are** signed, the issue is that they are signed with a self-made (self-signed) code signing certificate. You can read about it here: https://www.betterbird.eu/support/, quote:

We've since started self-signing all executables, you can [download](https://www.betterbird.eu/downloads/index.php) our certificate which you need to [install](https://www.betterbird.eu/support/certmgr.png) into "Trusted Root Certification Authorities" (check with certmgr.msc). The result looks like [this](https://www.betterbird.eu/support/uac.png).

It was previously suggested to use the services of the "SignPath Foundation" (signpath.io). They provide free code signing if the binaries are built using their CI and AppVeyor. So that's not practical, since Mozilla builds are complicated and the BB build even more so.

In the end, the issue is not the signing itself but to get a signing certificate at a reasonable price with a reasonable (low) amount of hassle. We started this last year with Sectigo (formerly Comodo) but cancelled the order after too much administrative issues. Note that SeaMonkey have actually managed to register a legal entity (the "SM Club") and obtained a certificate with this entity as the owner. That would be the desirable way forward.

**Comment by vsrt89** [comment]
I came across [this](https://www.reddit.com/r/opensource/comments/nl5u79/is_there_fossfriendly_certificate_authority_to/) discussion on reddit while looking for an affordable code signing certificate for opens source. It mentions polish [centrum.eu](https://shop.certum.eu/) that offers rather inexpensive code signing certificates for open source. It looks like:

- First time purchase requires a ["set"](https://shop.certum.eu/open-source-code-signing.html) of certificate and physical crypto card. Valid for a 1 year. Price is 69 EUR gross + shipping.
- [Renewal](https://shop.certum.eu/open-source-code-signing-code.html) is for 1 year and 25 EUR gross.
- Quite [strict requirements](https://support.certum.eu/en/code-signing-required-documents/) for identity validation.
- Certificate will be issued not for company but for developer as a person:
  - Open Source Code Signing are issued only for individuals
  - Issued certificate will contain „Open Source Developer” phrase added to the Common name field. Organization field will be set to „Open Source Developer”.

While I do prefer Bettrbird to be signed with non self-issued certificate, I'm not sure whether it worth the hassle.

**Comment by Betterbird** [comment]
The requirements look a little better than at Sectigo. There wanted an ID with street address, but in no country in the world known to me, the street address is in the passport. Alternatively they wanted me to go to a notary. This crowd is more realistic.

However, the certificate will only be issued to individuals, not the "Betterbird Project", as the current self-signed certificate says.

We'll look into it as workload allows.

**Comment by Betterbird** [comment]
We looked into it for five minutes. They deliver the certificate on a hardware token. It can't be exported from there. So we'd have to complete re-write the current signing pipeline from using PowerShell to using `signtool`. And fingers crossed that PIN entry isn't required for each of the 20 files that are signed.

**Comment by Betterbird** [comment]
Since we tweaked the signing scripts today, we have also revisited the Centrum offer. 70€ plus tax plus shipping comes to just under 110€. Their offer doesn't state the validity period, likely one year.

We also looked at their technical documentation, which is partly in Polish 😢. When singning with Windows `signtool`, each invocation requires PIN entry. So we'd have to restructure the entire process to only invoke the command once with all the files. Overall, it doesn't appear to be an attractive offer.

**Comment by vsrt89** [comment]
I agree. PIN entry on each release build will be quite a hassle and no friendly to build automation.
Better put the efforts somewhere else, than fighting with the third party signing certificate.

**Comment by Betterbird** [comment]
Difficult issue. Of course a properly signed product would be more attractive. But
https://support.certum.eu/en/signing-the-code-using-tools-like-signtool-and-jarsigner-instruction/
https://files.certum.eu/documents/manual_en/Code%20Signing%20-%20signing%20the%20code%20using%20tools%20like%20Singtool%20and%20Jarsigner.pdf
clearly states that all the files need to be nominated on a unique command line calling `signtool`.

The issue isn't forgotten, but just cooked on a lower flame.

**Comment by Betterbird** [comment]
We revisited this today. Somehow Cetrum's cloud solution had escaped us. It's cheaper and since there is no hardware, there is no PIN entry. So we bought a certificate and are now waiting for the verification and activation process to complete. Hopefully we can sign the next version using the new certificate. Also see here:
https://blog.betterbird.eu/2026/01/whats-the-story-with-windows-smartscreen
