### ISSUE TITLE
betterbird-zh-bin on AUR may be outdated

### ISSUE THREAD

**Issue by Technetium1** [Betterbird/thunderbird-patches#73]
[betterbird-zh-bin](https://aur.archlinux.org/packages/betterbird-zh-bin) is not the same version as [the rest](https://aur.archlinux.org/packages?O=0&SeB=nd&K=betterbird&outdated=&SB=p&SO=d&PP=50&submit=Go) seem to be.

**Comment by Betterbird** [comment]
Yes, currently we're not shipping BB 102.x for zh-CN since this localisation is incomplete for TB:
https://pontoon.mozilla.org/projects/thunderbird/
![image](https://user-images.githubusercontent.com/86832723/188710852-9af94367-8411-4d9d-b6ba-9afa89356cba.png)
There are about 100 missing strings. If the localisation ever catches up, we can ship BB 102.x in zh-CN, otherwise we'll have to drop it.

**Comment by Betterbird** [comment]
This was updated to 91.13.1 now. The Chinese localisation is just too incomplete for a fully localised package. If you want to use Chinese in 102, please install the language pack: https://www.betterbird.eu/downloads/LanguagePacks/zh-CN-102.3.0-bb17.xpi.

Additionally, contact the people in charge: https://pontoon.mozilla.org/zh-CN/thunderbird/contributors/.

Or alternatively, we can ship zh-TW which is complete. Let us know.

**Comment by Technetium1** [comment]
I'm a monolingual American, so I can't really say what is the right choice, but I would create a separate package for a separate locale if in doubt. In the meantime, the language pack seems like a perfectly valid solution.
