### ISSUE TITLE
Icons resemble Firefox too much on the taskbar

### ISSUE THREAD

**Issue by NuxRo** [Betterbird/thunderbird-patches#83]
Hi,

I have a small usability problem, the small icon of BB on the (MATE) taskbar is quite similar to Firefox'. It often takes me a bit to distinguish BB from FF, I didn't have this problem with TB.

As such I went ahead and black-filled in Gimp the red portions on the icons shipped in the tarball, it's better now (for me).

It is perhaps something you might want to address in the future.

Regards

**Comment by Betterbird** [comment]
We've heard the comment before. The colour is part of the registered trademark. The issue is discussed on our website:

Colours

The red-orange colour scheme is part of the registered trademark. Red-orange together with a Phoenix-like bird on one hand signify a more aggressive policy and on the other hand a [resurrection](https://www.deviantart.com/genzoman/art/Phoenix-202798063) from the ashes unleashing the potential of the product while not being bogged down by annoying bugs.

We've had many requests to change the icons to make them better distinguishable from Firefox to avoid mis-clicks. As the colour scheme is part of the trademark, this is unlikely to happen.

Due to the current situation in Europe, we were featuring the Betterbird logo at this website in Ukrainian colours from March to July 2022. This has now be replaced by a ribbon of solidarity.

If you want to make your own custom icons, download the green logo or the one in Ukrainian colours:
