### ISSUE TITLE
Attach signature from a file (txt, HTML, image) not working

### ISSUE THREAD

**Issue by fsarrias** [Betterbird/thunderbird-patches#84]
Hello
I have installed Betterbird 102.3 in Fedora 36 as a flatpack and I have copied my Thunderbird 102 profile to it.
Since then, my HTML file based signatures do not longer show when writting in mails (in Thunderbird worked fine.
I attach an image of the configuration option of HTML file containing the signature I was using without problem in Thunderbird and since migrating to Betterbird it does not show when writing the messages.

![HTMLfileSIGNATURE](https://user-images.githubusercontent.com/48757758/193250868-8ccdef29-2cf5-41cf-a1f0-8203ad69c6fd.png)

**Comment by Betterbird** [comment]
We can't reproduce this on Windows.
![image](https://user-images.githubusercontent.com/86832723/193255631-ce64ddfb-61c2-42e4-aa2d-f4a6331f5ebc.png)
We draw a red frame around the signature using userCotent.css, so it's visible:
```
.moz-signature {
  background-color: lightgrey !important;
  border: 1px solid red;
}
```
We get all sorts of bugs saying "works in TB, doesn't work in BB", but it's always due to different config. Please run TB on the BB profile and vice versa. BB has no changes from TB in the area.

**Comment by fsarrias** [comment]
I have solved it by placing the signature files inside the directory  $HOME/.var/app/eu.betterbird.Betterbird/Signatures so probably the issue has to do with some linux filesystem permissions. Thanks for your quick reply.

**Comment by Betterbird** [comment]
@mfschumann: Would it make sense to add this to the FlatPak readme file, there's just been another query here:
https://www.thunderbird-mail.de/forum/thread/90644-betterbird-102-3-2-bb19-64-bit-flatpak-linux-mint-19-3-signaturen-text-grafik-fu/

**Comment by mfschumann** [comment]
I've added this to the list of issues in the flatpak Readme section about lacking permissions.
