### ISSUE TITLE
Confirm Security Exception Menu Not Working (At Account Creation)

### ISSUE THREAD

**Issue by ekianjo** [Betterbird/thunderbird-patches#89]
The issue is as follows.
I have an email account that connects to a server that hosts several accounts from different domain names and therefore the certificate is not standard. When trying to connect for the first time, Betterbird  (just like Thunderbird) has a popup asking to confirm that this security exception is expected. 

Clicking on the button "confirm security exception" works in Thunderbird, but in Betterbird, the button does nothing and only "cancel" works.

**Comment by Betterbird** [comment]
We get all sorts of bugs saying "works in TB, doesn't work in BB", but it's always due to different config. Please run TB on the BB profile and vice versa. BB has no changes from TB in the area.

We get those security exceptions, too, and can't see that confirmation doesn't work:
![image](https://user-images.githubusercontent.com/86832723/193447850-6d7a6bb2-a373-492f-91ac-aefaa8ec1d1c.png)

**Comment by Betterbird** [comment]
I've read your report again. My screenshot is from the account setup, I guess your problem comes from "normal" operation where the account has already been set up. Recently TB fixed [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1735803) in their development version. That said, operation in TB and BB 102.x should be identical.

**Comment by ekianjo** [comment]
Ok let me clarify - this happens at account creation time as I was trying Betterbird for the first time. You were however right one your first message, I went back and check Thunderbird flatpak version, and there's the same problem. Because of this issue I cannot add an account at the moment. My other thunderbird install on another machine is not a flatpak one (repository of the distro instead) and works properly. Not sure where the issue is exactly coming from.

**Comment by Betterbird** [comment]
Thanks for the clarification. There's nothing we can action here. Account setup is unmodified in BB when compared to TB and additionally, the certificate handling takes place in the so-called Mozilla platform code in the Certificate Manager, for example the exception panel is this:
https://searchfox.org/mozilla-central/source/security/manager/pki/resources/content/exceptionDialog.xhtml

As we wrote, we've seen this issue where the exception couldn't be accepted. We recommend to use the Certificate Manager in your working profile (Settings, Privacy & Security, Manage Certificates) to inspect the exceptions in the "Servers" tab and any additional "Authorities" you might have imported. For memory, we fixed a similar case by importing the authority certificate first before being able to accept a related exception. If you make it work by carefully looking at the working profile, please document your steps in order to avoid having to repeat the investigation later on.
