### ISSUE TITLE
Compose in tab (Thunderbird enhancement 449299)

### ISSUE THREAD

**Issue by armaccloud** [Betterbird/thunderbird-patches#90]
This request is for two setting(s) to 
Automatically (on click `write` button) to open the compose email window to open in a new tab
Automatically (on click `reply` or `reply-to-all` button) to open the compose email window to open in a new tab

**Comment by Betterbird** [comment]
"Compose in tab" has been on the cards for a long long time, see: https://bugzilla.mozilla.org/show_bug.cgi?id=449299.
There's some sort of patch here https://gist.github.com/liamzebedee/5055929, and according to [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=449299#c178) there was some funding at https://freedomsponsors.org/issue/119/, but that site no longer exists. Maybe it moved to Bountysource.

And there's an old add-on: https://addons.thunderbird.net/en-US/thunderbird/addon/compose-for-thunderbird/

**Comment by armaccloud** [comment]
Thank you for your fast answer.
Is this something that betterbird might consider developing?
Or are you not developing new functionality aside from Thunderbird (only bug fixes)?

**Comment by Betterbird** [comment]
We're considering it. We've implemented a few things people wanted and TB isn't doing, like the multi-line view, complex search terms, search in encrypted messages, etc., see https://www.betterbird.eu/#featuretable.

From an effort and ongoing maintenance point of view "compose in tab" is the biggest ask to date. We know since our project leader used to be "Thunderbird compose peer".

**Comment by Betterbird** [comment]
There is a bunch more material on this, but it was never finished off and all the code and patches likely don't work/apply any more.
https://blog.mozilla.org/labs/2010/09/2756-bugs-found/ - Video: https://vimeo.com/14657225 - Repo: https://github.com/protz/Compose

Looking at https://gist.github.com/liamzebedee/5055929, that's actually very little, it merely replaces calls to `OpenComposeWindow[WithParams]` with `OpenComposeTab[WithParams]` and includes a new file `msgComposeTab.js`, but sadly that file isn't there. @liamzebedee, was that code ever written? This ["roadmap"](https://bug449299.bmoattachments.org/attachment.cgi?id=8601508) mentions: _Make a tab ... New tab is working, but parameters haven't been passed_. Maybe the author forgot to do a `hg add msgComposeTab.js` to add the new file to the patch ☹️. [This comment](https://bugzilla.mozilla.org/show_bug.cgi?id=449299#c130) states: _I've created a new JS module msgComposeTab.js, rewritten [nearly] all of the calls to OpenComposeWindow/OpenComposeWindowWithParams to this new JS module._ So where is it?

**Comment by Betterbird** [comment]
(Not totally) surprisingly, when you issue
`openContentTab("chrome://messenger/content/messengercompose/messengercompose.xhtml", "tab")` in the console and then hide the navigation/URL bar, you get this. Try it yourself. It's even partly functional.
![image](https://user-images.githubusercontent.com/86832723/194721005-8078ca22-f4d9-4172-ad5d-3f483585ce78.png)
Maybe it's not too hard after all. https://bugzilla.mozilla.org/show_bug.cgi?id=449299 has heaps of votes and this could be the next Betterbird killer feature 😃. The double menu is not too crash hot. We'll look into it further.
P.S.: It will cause a lot of strive with add-ons which expect a compose window.

**Comment by armaccloud** [comment]
This is good news, thank you for looking into this! The bug report you mentioned was opened 14 years ago :)
Would be great if this were integrated into Betterbird.

**Comment by Betterbird** [comment]
https://github.com/Betterbird/thunderbird-patches/commit/76c1eaeab89d69b932ed5f429958a45f381e29a4 is very much work in progress. Here's a likely incomplete list of all the stuff that **doesn't yet work**:
1. Right click (context menu) in compose area
2. Drag attachment
3. Color picker, most of the other formatting seems to work
4. Send closes window
5. Status bar CSS
6. Add-ons like ThunderHTMLedit don't work (since they attach to compose **windows**)
7. Reply, forward, edit draft, edit as new, etc. (untested, likely not working), save composition as HTML/plaintext.
8. Restore tab content after restart
9. Save draft when window/tab is closed.

**Comment by Betterbird** [comment]
People ask where this is going: "Drag attachment" is blocked by an upstream issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1795487

**Comment by Betterbird** [comment]
Despite some considerable effort invested into this, it's likely not going to be implemented due to architectural issues, the worst being that without a stand-alone compose window, all add-ons working on the compose window will stop working since the rely on working in a window with a certain internal URL (chrome://messenger/content/messengercompose/messengercompose.xhtml).

**Comment by armaccloud** [comment]
Thank you, @Betterbird, for putting so much effort into researching the possibilities for this.
