### ISSUE TITLE
Tag 102.4.0-bb21

### ISSUE THREAD

**Issue by mfschumann** [Betterbird/thunderbird-patches#93]
I just stumbled upon https://www.betterbird.eu/releasenotes/index.html stating that 102.4.0-bb21 has been released already. Would you mind tagging the commit so I can build the flatpak from it? Thanks!

**Comment by Betterbird** [comment]
Last I checked in the (European) afternoon, TB hadn't shipped the build. There's always a chance that they will build again, that's why I'm waiting. Now they've shipped at 20:00: https://treeherder.mozilla.org/jobs?repo=comm-esr102

I'll apply the patch now. Would you mind using e-mail for issues like this in the future?
